### PR TITLE
Fix typo in metrics/sdk

### PR DESCRIPTION
**Pull request by pichlermarc**
Fixes a typo in `specification/metrics/sdk.md`.

### CODE REVIEW

**Review by MrAlias — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Something is wrong with github, this has enough approvals, but doesn't get auto-merged.

**Comment by tigrannajaryan** [comment]
Closing and reopening didn't help either. @pichlermarc you may need to re-create the PR (unless someone else knows how to convince github to merge this).

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
@pichlermarc you need to rebase this.

**Comment by bogdandrutu** [comment]
@arminru you may want to merge this since you have also access to update the PR.

**Pull request merged**
