### PR TITLE
Change http.server.duration and http.client.duration units to seconds

### LINKED ISSUE #3389: Change http.server.duration and http.client.duration units to seconds
**What are you trying to achieve?**

Follow the decision that was made in #2977 and change `http.server.duration` and `http.client.duration` units to seconds.

### PR DESCRIPTION
**Pull request by trask**
Fixes #3389

## Changes

Changes `http.server.duration` and `http.client.duration` units to seconds.

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Do we feel this is requires a similar advance notice treatment as other http convention changes or we think it is obscure enough and will have minimal impact? Do we know if this is widely implemented by our existing instrumentations?

**Comment by trask** [comment]
the aberration here is Java agent instrumentation which has been emitting these metrics for ~1 year

we are already considering [bumping the Java agent to 2.x with the upcoming ECS alignment changes](https://github.com/open-telemetry/opentelemetry-java-instrumentation/issues/8280) and may choose to bundle this change into that update as well

**Review by jsuereth — APPROVED** [review]

**Comment by trask** [comment]
> > Do we know if this is widely implemented by our existing instrumentations?
> 
> It is definitely not widely used, only few SDKs have released stable version of metrics, and just started HTTP metrics instrumentation experimental work.

we discussed in HTTP semconv stability WG, and our recommendation is that the transition plan for this change be left up to the language maintainers, with this general guidance:
* if http metric instrumentation has been in wide use for a while (e.g. Java), it's probably good to bundle this change in with the upcoming HTTP semconv changes

cc @open-telemetry/opentelemetry-python-contrib-maintainers @open-telemetry/cpp-maintainers @open-telemetry/javascript-maintainers @open-telemetry/go-maintainers @open-telemetry/dotnet-maintainers @open-telemetry/dotnet-contrib-maintainers

**Comment by MrAlias** [comment]
> Do we know if this is widely implemented by our existing instrumentations?

As a data point: It is implemented in the, non-stable, Go instrumentation [`otelhttp`](https://pkg.go.dev/go.opentelemetry.io/contrib/instrumentation/net/http/otelhttp).

**Pull request merged**
