### PR TITLE
Current state of PHP in spec-compliance-matrix.md

### PR DESCRIPTION
**Pull request by bobstrecansky**
Fixes https://github.com/open-telemetry/opentelemetry-php/issues/167

## Changes

Filling in the implementation matrix to show the current state of the PHP project.

Related issues #
https://github.com/open-telemetry/opentelemetry-php/issues

Related [oteps](https://github.com/open-telemetry/oteps) #
N/A

### CODE REVIEW

**Comment by bobstrecansky** [comment]
I've signed the EasyCLA; not certain as to why it's showing up as missing in this CI check.

**Comment by bobstrecansky** [comment]
@tigrannajaryan - I was planning on performing that in a separate commit.  Just did so.

**Comment by bogdandrutu** [comment]
Please sign the CLA :)

**Comment by bogdandrutu** [comment]
@bobstrecansky do you have the email that you used to sign the CLA assign to the account and used in the commits (git config email)?

**Comment by bobstrecansky** [comment]
Yup; it should be bob.strecansky@gmail.com.  I opened a PR to the PHP project right after that accepted my signed CLA, which seems strange to me.

**Comment by bobstrecansky** [comment]
Ahh, yes - this is my mistake.  I cloned it on a computer that I don't normally use for OpenTelemetry work (I'm on vacation) - this is where my problem lies.

**Comment by tigrannajaryan** [comment]
@open-telemetry/technical-committee please merge this to help avoid merge conflicts.

**Review by arminru — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
