### PR TITLE
Add tracer construction spec

### LINKED ISSUE #39: Document Java API: Tracer construction
[Java repo](https://github.com/open-telemetry/opentelemetry-java) was used to combine APIs from OpenTracing and OpenCensus. 
Most of APIs are ready to be documented in a form of cross-language specification. 

Tracing class construction needs to be described. Tracer for specific library. Global Tracer, etc.

### PR DESCRIPTION
**Pull request by pavolloffay**
Resolves #39 

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
I have a couple concerns here.
  * Not sure how language-neutral the proposed pattern is. In Go people often have very strong feelings against registration pattern.
  * I think there have been many asks in OpenTracing where people use multiple tracers per process, so using words like "MUST use `opentelemetry.GetTracer()`" sounds too rigid

**Comment by carlosalberto** [comment]
Hey @pavolloffay thanks for cooking this PR.

As Yuri said, I think stating "MUST" for using `OpenTelemetry.getTracer()` is indeed strong - probably it's better to leave it as a recommendation only.

Also, automatic registration (i.e. what `TracerProvider` does) may not even be possible in all the languages (in Python, for example). Perhaps we can mention this as a possible route for languages to register `OpenTelemetry.get*()` members, or else fallback to manual registration.

**Comment by pavolloffay** [comment]
> Not sure how language-neutral the proposed pattern is. In Go people often have very strong feelings against registration pattern.

**Comment by pavolloffay** [comment]
> I think there have been many asks in OpenTracing where people use multiple tracers per process, so using words like "MUST use opentelemetry.GetTracer()" sounds too rigid

I think we should look at it from the other side. We should assure that the registry always returns a valid tracer so the instrumentations can bind to it.

**Comment by SergeyKanzhelev** [comment]
@iredelmeier for libraries instrumentation there must be a way to obtain the `Tracer` without the need to accept it as an argument thru dependency injection. Thus `OpenTelemetry.getTracer()` must exists. Even if customer is not relying on it. Do you envision a future when every library takes `OpenTelemetry` object as an argument on construction?


As for non-null - an implementation of this registry may be very language specific. But I'd say the requirement for it to be non null is quite important to avoid undesired `NullReferenceException`s. It's not too hard to return an noop tracer.

**Comment by iredelmeier** [comment]
> @iredelmeier for libraries instrumentation there must be a way to obtain the `Tracer` without the need to accept it as an argument thru dependency injection. Thus `OpenTelemetry.getTracer()` must exists. Even if customer is not relying on it. Do you envision a future when every library takes `OpenTelemetry` object as an argument on construction?

One in which every library **requires** providing a tracer? No. One in which libraries are at least advised to **enable** overriding the global? Yes.

> As for non-null - an implementation of this registry may be very language specific. But I'd say the requirement for it to be non null is quite important to avoid undesired `NullReferenceException`s. It's not too hard to return an noop tracer.

My thoughts exactly! e.g., in OpenTracing there's the concept of a [`NoopTracer`](https://github.com/opentracing/specification/blob/master/specification.md#nooptracer), which conforms to the same interface but (as the name implies) doesn't actually do anything. (I'd actually argue that OpenTelemetry should take this a step *further* with, e.g., a `NoopSpan`, but that's a separate conversation.)

**Comment by SergeyKanzhelev** [comment]
@iredelmeier I suggest we file a feedback item to expand this description for the languages that uses DI extensively and have a practice of constructing SDKs and providing OT object explicitly. In any case there must be some global object to get as minimum the default (noop) tracer.

So I suggest we merge this one and formulate it better later.

I'd need this update personally for C#, but not ready to generalize it properly as a spec

**Comment by SergeyKanzhelev** [comment]
Created: https://github.com/open-telemetry/opentelemetry-specification/issues/143

**Pull request merged**
