### PR TITLE
Move TraceState operations description from SDK to API

### PR DESCRIPTION
**Pull request by iNikem**
After #905 was merged I was approached by JavaScript and Java SIGs, who brought to my attention that in these languages `Propagators` currently depend only on API, not SDK. As `Propagators` are the most common users of the `TraceState` API, I hereby try to remedy the situation and propose to move it from SDK specification to the API.

### CODE REVIEW

**Comment by iNikem** [comment]
@dyladan

**Review by dyladan — APPROVED** [review]
Thanks :)

**Review by tsloughter — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Comment by carlosalberto** [comment]
Marking it as Required for GA, as this breaks the API (for good, hopefully :) )

**Review by Oberon00 — APPROVED** [review]
This should mostly document the status quo and is sensible enough 👍

**Comment by carlosalberto** [comment]
@open-telemetry/specs-approvers Please review this change.

**Review by arminru — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Pull request merged**
