### PR TITLE
Move Metrics API spec to Stable

### PR DESCRIPTION
**Pull request by reyang**
Discussed during the [11/4/2021 Metrics SIG Meeting](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#heading=h.kf8ygsem4izr), the Metrics API spec has reached Feature-freeze since 7/31/2021, and been prototyped / used by multiple languages. In the past month there was no issue reported. We're ready to move to Stable 🚀.

### CODE REVIEW

**Review by cijothomas — APPROVED** [review]

**Review by MikeGoldsmith — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Review by utpilla — APPROVED** [review]

**Review by jonatan-ivanov — APPROVED** [review]

**Review by mottibec — APPROVED** [review]

**Review by pirgeo — APPROVED** [review]

**Comment by tomkerkhove** [comment]
I presume the timeline on https://github.com/open-telemetry/opentelemetry-specification/milestone/15 is no longer up to date then?

**Comment by carlosalberto** [comment]
@reyang We will be having a Spec release this week. Do you think we should include this or should we hold on?

**Comment by reyang** [comment]
> @reyang We will be having a Spec release this week. Do you think we should include this or should we hold on?

Yes, we should include this.

**Comment by reyang** [comment]
> I presume the timeline on https://github.com/open-telemetry/opentelemetry-specification/milestone/15 is no longer up to date then?

I'll make the update tmr.

**Review by codeboten — APPROVED** [review]
🎉

**Review by jmacd — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Review by jonatan-ivanov — APPROVED** [review]

**Comment by alolita** [comment]
Excellent work @reyang and all OTEL metrics contributors!!! Great to see this PR.

**Pull request merged**
