### PR TITLE
Update spec compliance for JS

### PR DESCRIPTION
**Pull request by dyladan**
I have added + and - where I am sure, but left blank where I am not.

/cc @mayurkale22 @obecny

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Comment by SergeyKanzhelev** [comment]
CC: @open-telemetry/javascript-approvers

**Comment by SergeyKanzhelev** [comment]
this is uncontroversial, happy to merge as it is and have a follow up PRs for blanks. Or wait if it works better for you

**Comment by tigrannajaryan** [comment]
@SergeyKanzhelev yes, please merge to avoid conflicts if other languages update the same rows.

**Comment by obecny** [comment]
## Exporters
Concurrent sending - I think we can say yes as we are not blocking next sending before previous finishes
Honors retryable responses with backoff  - currently we are not retrying anything in any exporter
Honors non-retryable responses - the same
SpanKind mapping - yes in zipkin 
InstrumentationLibrary mapping - zipkin no
Service name mapping - only zipkin is setting service name from resources if service name is not provided, all other exporters (zipkin too) sets this via config

**Comment by tigrannajaryan** [comment]
@obecny can you please submit a PR with the updates you have?

**Pull request merged**
