### PR TITLE
ParentBased is a decorator

### PR DESCRIPTION
**Pull request by pellared**
ParentBased sampler is decorator (and not a composite).

> The intent of a composite is to "compose" objects into tree structures to represent part-whole hierarchies.

> What problems can the Composite design pattern solve? 
> [...]
> A part-whole hierarchy should be represented as tree structure

`ParentBased` does not produce a tree.  Composite aims to solve a different (but kind of similar) problem.

> decorator pattern [...] that allows behavior to be added to an individual [object](https://en.wikipedia.org/wiki/Object_(computer_science)), dynamically, without affecting the behavior of other objects from the same [class](https://en.wikipedia.org/wiki/Class_(computer_science)).

> What problems can it solve?
> Responsibilities should be added to (and removed from) an object dynamically at run-time.[5]
>>A flexible alternative to subclassing for extending functionality should be provided.

The key feature of the `ParentBased` is how it changes the "behavior" of the wrapped sampler. We decorate the existing sampler so that it handles the sampling based on the parent's span.

References:
- https://en.wikipedia.org/wiki/Decorator_pattern
- https://en.wikipedia.org/wiki/Composite_pattern
- https://sourcemaking.com/design_patterns/composite
- https://sourcemaking.com/design_patterns/decorator
- https://stackoverflow.com/questions/2233952/difference-between-the-composite-pattern-and-decorator-pattern

Related issue https://github.com/open-telemetry/opentelemetry-go/issues/4565

### CODE REVIEW

**Review by yurishkuro — APPROVED** [review]

**Comment by yurishkuro** [comment]
image

**Comment by MrAlias** [comment]
I am not in favor of using explicitly object-oriented language to describe things in the specification given many languages that implement it are not object-oriented. Also, the implementation of this sampler can quite literally be a decision hierarchy tree matching what you define as "composite". I think the current definition is correct.

**Comment by yurishkuro** [comment]
Decorator is a design pattern that means "modifies behavior of underlying thing without changing its interface". A function can decorate another function, there's nothing inherently object-oriented about it.

In contrast, "composite" means containing more than one other thing, and doesn't imply anything about the resulting interface. In the context of ParentBased sampler decorator is a better term.

**Review by tigrannajaryan — APPROVED** [review]
This is a modification to a Stable doc. I believe we are allowed to do since it does not change any contract or behavior, it merely uses a more correct terminology.

**Review by trask — APPROVED** [review]

**Pull request merged**
