### PR TITLE
Mark cardinality limits as Stable

### LINKED ISSUE #3904: Stabilize Overflow attribute section under Cardinality Limits
**What are you trying to achieve?**

Mark the [Overflow attribute](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#overflow-attribute) section under Cardinality limits as **Stable**.

The spec was updated with the overflow attribute and cardinality limits section in #2960.

It looks like we already have more than three languages that have added support for this:
- [Go](https://github.com/open-telemetry/opentelemetry-go/blob/main/sdk/metric/internal/aggregate/limit.go#L22) https://github.com/open-telemetry/opentelemetry-go/pull/4457
- [C#](https://github.com/open-telemetry/opentelemetry-dotnet/blob/main/src/OpenTelemetry/Metrics/AggregatorStore.cs#L402) https://github.com/open-telemetry/opentelemetry-dotnet/pull/4737
- [Java](https://github.com/open-telemetry/opentelemetry-java/blob/main/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java#L27) https://github.com/open-telemetry/opentelemetry-java/pull/5560
- [Rust](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry-sdk/src/metrics/internal/aggregate.rs#L21) https://github.com/open-telemetry/opentelemetry-rust/pull/1066

### PR DESCRIPTION
**Pull request by reyang**
Mark cardinality limits as Stable.

Fixes #3904

These are the language implementations:
  * .NET https://github.com/open-telemetry/opentelemetry-dotnet/blob/60b7d9baf32ee437ba3e84f1886ba8917e8d9475/src/OpenTelemetry/Metrics/AggregatorStore.cs#L457
  * Go https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/sdk/metric/internal/x/README.md?plain=1#L14 and https://github.com/open-telemetry/opentelemetry-go/blob/6731dc70900c4e5e47e00eb0340865189a5d1a76/sdk/metric/internal/aggregate/limit.go#L11
  * Java https://github.com/open-telemetry/opentelemetry-java/blob/fa826fdef07167b22089b96b957749e9f41e72e2/sdk/metrics/src/main/java/io/opentelemetry/sdk/metrics/internal/state/MetricStorage.java#L27
  * Rust https://github.com/open-telemetry/opentelemetry-rust/blob/d652dc82fcb828909877c3492f85d3a8206efd6e/opentelemetry-sdk/src/metrics/mod.rs#L2017

## Changes

Please provide a brief description of the changes here.

For non-trivial changes, follow the [change proposal process](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#proposing-a-change).

* [X] Related issues
  * #3813 There was a [Technical Committee meeting on Sep. 25th](https://docs.google.com/document/d/1hOHPCu5TGenqTeWPB9qQB_qd33uITZBcvK1FnWxYJAw/edit#heading=h.y4jtvl5jpsok), we don't think this is a blocking issue. @MrAlias raised it up and I'm clarifying with him whether it is a blocker. https://github.com/open-telemetry/opentelemetry-specification/pull/4222#issuecomment-2379918841
  * #3578
  * #3798
  * #3866 (the blocking part has been addressed by #3856 and #3906, the issue will remain open to track the other parts and those are not blocking the stabilization)
* [ ] Related [OTEP(s)](https://github.com/open-telemetry/oteps) #
* [X] Links to the prototypes (when adding or changing features)
* [X] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

### CODE REVIEW

**Review by jack-berg — APPROVED** [review]

**Review by pellared — APPROVED** [review]

**Comment by cijothomas** [comment]
There are few issues that were raised earlier on this topic. We should mark them as resolved (and close the issue), or mark them as non-blocking for stability for cardinality limits.
https://github.com/open-telemetry/opentelemetry-specification/issues/3904#issuecomment-1976763534

**Comment by reyang** [comment]
> ... or mark them as non-blocking for stability for cardinality limits

How do you want to mark them as non-blocking? @cijothomas

**Comment by MrAlias** [comment]
I feel [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3813) needs a resolution before this can become stable.

**Comment by cijothomas** [comment]
> > ... or mark them as non-blocking for stability for cardinality limits
> 
> How do you want to mark them as non-blocking? @cijothomas

TC can leave a comment on the issues saying "it is not a blocker for stabilizing cardinality limits feature spec".
(I don't think it worth creating github labels like blocking-cardinality-stable, allowed-cardinality-stable, nice-to-have-cardinality-stable etc, so a simple comment can help.)

**Comment by reyang** [comment]
> I feel [this issue](https://github.com/open-telemetry/opentelemetry-specification/issues/3813) needs a resolution before this can become stable.

@MrAlias Is this something that cannot be an additive change later, and must be resolved now? Would you help to clarify? Thanks!

**Comment by jmacd** [comment]
@reyang My opinion is that #3813 should not be a blocker. We are trying to impose a limit on the SDK without specifying the exact mechanism that it uses, because SDKs will take different and reasonable approaches to aggregation, and all that matters is that they reach a limit and respect it. How the limit is reached and respected is an implementation detail, and when the limit is reached the telemetry coming from an application is degraded, that is all that I expect from cardinality limits.

**Review by jmacd — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
