### PR TITLE
Prepare for the metrics SDK experimental release

### PR DESCRIPTION
**Pull request by reyang**
This PR is pending on #1888 and #1913 to be merged.

Changes:
* Removed the warning & banner.
* Updated changelog.

### CODE REVIEW

**Comment by jack-berg** [comment]
Hi @reyang - I'm curious to get your (and others) thoughts on when best to resolve Issue #1902 regarding some sort of support for a min, max, sum, count style aggregation.

The current thought is that we can achieve this by [extending the histogram proto](https://github.com/open-telemetry/opentelemetry-proto/pull/279) with optional min / max fields. If we went down this route, it would be nice to have this type of histogram specified in the SDK spec. Specifically, I think we could add a `Zero Bucket Summary Histogram Aggregation` specification akin to the [Explicit Bucket Histogram Aggregation](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/sdk.md#explicit-bucket-histogram-aggregation). 

Personally, I think it would be valuable to make this aggregation available in the experimental release.

**Comment by jsuereth** [comment]
@jack-berg Adding min/max fields to histogram proto would be part of "metrics data model" specification.   If we add min/max there, then implicitly histogram aggregators will need to be updated to support it.  I think that, combined with providing no buckets to histogram explicit bucket will get you exactly what you want out of `Summary` from the `Histogram` instrument type.


Happy to help shepherd you through the process and drive Prs on appropriate repositories.

**Comment by reyang** [comment]
@jack-berg thanks for calling this out. I think these are not blockers for SDK spec Experimental release, and this is definitely a nice-to-have and we should get it before Feature-freeze. Here goes the [Metrics SIG meeting notes](https://docs.google.com/document/d/1pdvPeKjA8v8w_fGKAN68JjWBmVJtPCpqdi9IZrd6eEo/edit#).

There are several parts I could imagine:
1. The data model spec (which is Stable) has to be updated.
2. The proto has to be updated, using the protobuf v3 OPTIONAL.
3. The SDK/View might need to be updated so folks can specify if they want to spend the extra CPU/memory to get min/max, and whether it should be opt-in (default off) or opt-out (default on).

**Review by jmacd — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]
Approved, pending PRs listed as blocking.

**Review by cijothomas — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Pull request merged**
