### PR TITLE
Add outcome label for http conventions for metrics (only)

### PR DESCRIPTION
**Pull request by ebullient**
Add `outcome` as a label for http metrics that makes it easier to create queries for successful vs. unsuccessful requests (e.g.) without having to deal with querying/grouping multiple status codes. 

## Changes

Add an optional `outcome` label to the semantic conventions for metrics.

Related issues #

From https://github.com/open-telemetry/opentelemetry-specification/pull/739#issuecomment-669609233

### CODE REVIEW

**Comment by Oberon00** [comment]
Is it OK to have the metric and span semantic conventions diverge here? Maybe it would be better to add a generic otel.status label based on #966?

**Comment by ebullient** [comment]
I stuck w/ my original suggestion from the other PR (as was requested), as I know this convention is already in use in several places. 

I could argue that #966 still results in a few too many values than is useful for metrics. If you have the status code and the outcome, you don't need the additional categories, do you?

**Comment by ebullient** [comment]
As an aside, I also find using the `http.` prefix for labels on http metrics to be really redundant...

**Comment by kenfinnigan** [comment]
+1 from me

**Comment by justinfoote** [comment]
I'm still working out whether I approve of the PR or not, but here are my thoughts:

* The `http.outcome` label doesn't _add_ any information -- it's simply a convenience for query systems that don't have great support for range clauses (`WHERE http.status_code >= "200" AND http.staus_code < "300"`) or for like clauses (`WHERE http.status_code LIKE "2%"`). If there is broad requirement for convenience labels like this, I'm not necessarily against it, but it feels like a slippery slope, and if possible I'd prefer to keep this out of the semantic conventions, and suggest that they belong in a downstream processor, exporter, or in a back-end's ingest pipeline.
* Is the name "outcome" standard? The [http spec](https://tools.ietf.org/html/rfc2616#section-10) refers to the hundreds place of the status code as the _class_.
* If this actually is something that seems valuable, I don't understand why we'd want it for metrics and not for traces. 

And I know this was an aside, but I believe the `http.` prefix makes sense. It gives us consistency between metrics and traces. And I like how it clarifies which labels are really http-specific and which ones are not. There may be additional labels added by application developers or service operators, and having ours neatly namespaced I think helps with clarity. This got more discussion in https://github.com/open-telemetry/oteps/pull/108. If this doesn't make sense for one tracing back-end, I think the labels should be trimmed in an exporter or in the ingest pipeline.

**Comment by ebullient** [comment]
> I'm still working out whether I approve of the PR or not, but here are my thoughts:
> 
>     * The `http.outcome` label doesn't _add_ any information -- it's simply a convenience for query systems that don't have great support for range clauses (`WHERE http.status_code >= "200" AND http.staus_code < "300"`) or for like clauses (`WHERE http.status_code LIKE "2%"`). If there is broad requirement for convenience labels like this, I'm not necessarily against it, but it feels like a slippery slope, and if possible I'd prefer to keep this out of the semantic conventions, and suggest that they belong in a downstream processor, exporter, or in a back-end's ingest pipeline.
> 
>     * Is the name "outcome" standard? The [http spec](https://tools.ietf.org/html/rfc2616#section-10) refers to the hundreds place of the status code as the _class_. Perhaps a more fitting name would be `http.status_code.class`.
> 
>     * If this actually is something that seems valuable, I don't understand why we'd want it for metrics and not for traces.
> 
> 
> And I know this was an aside, but I believe the `http.` prefix makes sense. It gives us consistency between metrics and traces. And I like how it clarifies which labels are really http-specific and which ones are not. There may be additional labels added by application developers or service operators, and having ours neatly namespaced I think helps with clarity. This got more discussion in [open-telemetry/oteps#108](https://github.com/open-telemetry/oteps/pull/108). If this doesn't make sense for one tracing back-end, I think the labels should be trimmed in an exporter or in the ingest pipeline.
> 
> After writing all of this, I think I've decided my position: I'm slightly opposed to this change, but I won't object if the group at large finds it useful.
> And if we do go ahead with it, I think I'd prefer a different name than "outcome".

The notion of "outcome" was introduced into micrometer in response to frequent user error (yes, this could be related to systems that don't have great support, but people are still going to use those systems...). Post #966, we're down to just Ok, Unset, and Error, which isn't sufficient, as there is a meaningful difference between client error and server error: all errors are not the same.

I would be fine with `http.status_class`

**Comment by justinfoote** [comment]
Cool, thanks! 
I agree than OK, UNSET and ERROR aren't sufficient granularity for most use cases, but in the case of HTTP, we have much higher granularity information in the `http.status_code` field. I'm not yet convinced that we need a medium granularity label that is derived from the status_code. 

And, if we as a group find this useful and decide to add it to the metrics semantic conventions, I don't love that it would diverge from the semantic conventions of traces only in this one field. I'd much prefer that it get added to both places if it gets added to either. 

I'd like to hear some others weigh in on this proposal.

**Comment by ebullient** [comment]
well.. we could revert some of the changes in 966, and bring it back to this grouping instead...

**Pull request closed without merging**
