### PR TITLE
Add Logs Glossary document

### PR DESCRIPTION
**Pull request by tigrannajaryan**
- Added the Glossary that is already approved as an OTEP:
  https://github.com/open-telemetry/oteps/blob/master/text/0091-logs-vocabulary.md

- Added a Logs Overview document with placeholder Table of Contents
  to serve as a place to link future logs-related documents from.

- Linked Logs Overview document from main README.md to make it discoverable.

### CODE REVIEW

**Comment by dyladan** [comment]
Why would we have a separate glossary for logs? Wouldn't it make sense to keep all definitions in the same file, and just link to it?

**Comment by tigrannajaryan** [comment]
Combined glossary also work for me. What do you others think? If most are on board with that approach I will change.

**Comment by bogdandrutu** [comment]
@tigrannajaryan I would combine them in the same file but with the structure of headers respecting the proposed structure of directories:

```
# Traces
....
# Metrics
...
# Logs
## Log foo
...
## Log bar
...
```

**Comment by dyladan** [comment]
You may want to also link directly to entries at time of first use

```markdown
When we initialize [logs foo](glossary.md#logs-foo) blah blah blah...
```

**Comment by tigrannajaryan** [comment]
I removed separate `logs/glossary.md` and moved the content to main `glossary.md`.

**Comment by bogdandrutu** [comment]
@open-telemetry/specs-approvers can you review?

**Comment by bogdandrutu** [comment]
@open-telemetry/specs-approvers ping :)

**Comment by carlosalberto** [comment]
Merging as we have enough approvals.

**Pull request merged**
