### PR TITLE
Drop log Name field

### LINKED ISSUE #2074: Is Name field necessary in Log Data Model
The log [data model](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md) currently has a Name field.

It is not entirely clear why this field is needed.

Some of the example mappings provided use it this way:
- Syslog - MSGID. Could be an Attribute["syslog.msgid"] instead to match how PROCID is handled.
- SignalFx Events - EventType. Could be Attributes["com.splunk.signalfx.event_type"] to match how Category is handled.
- CloudTrail Log Event - errorCode. Unclear where we put this. Attributes["cloudtrail.error_code"]?
- Google Cloud Logging - log_name. This appears to be incorrectly designed, see https://github.com/open-telemetry/opentelemetry-specification/issues/1808

In most of these cases it appears that it could be placed in Attributes. The unclear one is CloudTrail Log Event and probably Google Cloud Logging.

Can we come up with clear justifications of why the Name field must exist and why for example Body is not enough?

### PR DESCRIPTION
**Pull request by jack-berg**
Fixes #2074.

## Changes

Drop the Log `name` field.

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]
The mappings that previously used the Name field may require more discussion, but because in this document the mappings are _Examples_ I am fine with merging this PR as is and if necessary future PRs can make further changes to the example mappings.

After this is merged we need a corresponding change in the proto repository and it will be followed by a change in the Collector.

@open-telemetry/collector-approvers @open-telemetry/collector-contrib-approvers please review and comment if you believe your receiver/exporter absolutely needs this field to stay for some reason and cannot substitute it by an attribute with a format-specific semantic convention.

**Review by djaglowski — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]

**Review by dmitryax — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@jkwatson @pmm-sumo please review.

**Review by jkwatson — APPROVED** [review]

**Review by pmm-sumo — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Let's keep this open for a few more days, don't merge yet. I want to make sure more people are aware of the change.

**Comment by bogdandrutu** [comment]
Not sure about the impact, but I think the example of using "Attributes" to model different "schemas" for the logs is not very robust. I am ok removing it, but I would feel strong against using attributes to define "schema"

**Comment by tigrannajaryan** [comment]
> Not sure about the impact, but I think the example of using "Attributes" to model different "schemas" for the logs is not very robust. I am ok removing it, but I would feel bad about using attributes to define "schema"

@bogdandrutu which example are you referring to? I am also confused by the reference to "schemas". What do you mean by this?

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-logs-approvers please review.

**Comment by bogdandrutu** [comment]
@tigrannajaryan was referring to the issue.. as I said I think this is fine in general, but we should carefully think before making the standard of encoding different types of events/entries as logs and identify using attributes

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan was referring to the issue.. as I said I think this is fine in general, but we should carefully think before making the standard of encoding different types of events/entries as logs and identify using attributes

Got it. I have been thinking about this for a while now and it seems to fit nicely in how we understand the attributes are used how presence of attributes can indicate a "type" of the recorded information. For example let's say I want to record information about events happening in the browser. Instead of using the `Name` field I could for example have a semantic convention for an attribute named `browser.event_type` or `browser.dom.event_type` the presence of which indicates that it is a browser event and the value is a string that tells what exactly the event is.

Or for example Otel Collector may decide to emit events about its state, for example `otel.collector.state_change` with a value of "started" can indicate that the Collector is started and in that same log record also record a bunch other attributes that describe the Collector.

Essentially every domain (such as browser) needs to come up with a reasonable semantic convention for the event they want to describe.

**Review by cijothomas — APPROVED** [review]

**Review by zenmoto — APPROVED** [review]

**Comment by himanshpal** [comment]
The log name is really helpful since its always going to be low cardinality field & this improves the Search by a large factor compared to doing LIKE on Body for systems which store logging data in columnar format (parquet) & query via athena/presto.

Removing this field moves the responsibility back to lib consumer to make sure all attributes minimum have something similar in all lang sdk's.

**Comment by tigrannajaryan** [comment]
@himanshpal the problem with the existing Name field is that the community has not been able to come up with a clear definition of what it is supposed to reflect. The semantics are not clear and people have different opinions about what it is supposed to contain.

For your particular use case if you know what you want to record as the "name" you can do that as an attribute.

If in the future we manage to form a consensus around what the "name" means we do not preclude the possibility of adding the field back.

**Review by kumoroku — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Comment by jack-berg** [comment]
> Removing this field moves the responsibility back to lib consumer to make sure all attributes minimum have something similar in all lang sdk's.

@himanshpal one of the problems with `name` is that it lacks an unambiguous mapping for all known log and event formats, as argued [here](https://github.com/open-telemetry/opentelemetry-specification/issues/2074#issuecomment-996867783). So while its nice to have a low cardinality identifier, it's not particularly useful or guaranteed to be low cardinality unless the mapping semantics are well established. 

Instead, each log format can establish its own [mapping conventions](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/data-model.md#appendix-a-example-mappings). Folks doing analysis / search can use any type / classifiers available for format of logs they're analyzing.

**Comment by tigrannajaryan** [comment]
We have enough approvals, 2 business days since the last comment. Merging.

**Pull request merged**
