### PR TITLE
Use correct size in Span example

### PR DESCRIPTION
**Pull request by jaswdr**
Fixes **docs**

In the previous example, Span C was small then Span B, making the user misunderstanding that Span B and C happens at the same time, by changing the size of the Span C to be equal to Span B the user can understand that Span B and C are at the same level, having both Span A as parent.

## Changes

don't apply

Related issues **no**

### CODE REVIEW

**Review by Oberon00 — CHANGES_REQUESTED** [review]
I think this is intentional. Even though Span B and C are at the same level, they both have Span A as parent so they will not start at the exact same time.

**Comment by arminru** [comment]
I also think that the example is fine as is. The parent/child relationships are shown in the tree diagram right above and the timings in the chart below make sense.

**Comment by jaswdr** [comment]
@Oberon00 @arminru thank you for the feedback, I'm starting to study the open telemetry topic, and now I see that the time to start for Span B and C could be different, C could start after B, or B after C, in any case the example makes sense to show the reader that it doesn't want to show the hierarchy.

**Comment by arminru** [comment]
@jaswdr thanks for double-checking and making the effort to revise it, however!

**Pull request closed without merging**
