### PR TITLE
Invalidate entries for span limits env, because of the default changes

### PR DESCRIPTION
**Pull request by bogdandrutu**

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Comment by jkwatson** [comment]
I just noticed that the SDK section about SpanLimits still has `1000` as the defaults, rather than the `128` that the env vars specifies. Do you want to tweak that here, or should I put in a separate PR?

**Comment by bogdandrutu** [comment]
Yes bug :(

**Comment by bogdandrutu** [comment]
Rebase failed :)

**Comment by jkwatson** [comment]
> Yes bug :(. Please send a PR

#1429

**Review by iNikem — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Pull request merged**
