### PR TITLE
Python compliance matrix update

### PR DESCRIPTION
**Pull request by codeboten**
This change covers the resource and context propagation sections. It also updates the value for zipkin environment variables support.

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Comment by bogdandrutu** [comment]
Please rebase

**Review by tigrannajaryan — APPROVED** [review]
Please resolve the conflicts.

**Comment by tigrannajaryan** [comment]
@codeboten thanks. 

Admins, let's merge this to avoid more merge conflicts.

**Comment by codeboten** [comment]
Thanks for the quick review @tigrannajaryan @bogdandrutu!

**Review by arminru — APPROVED** [review]

**Comment by carlosalberto** [comment]
Merging fast to avoid conflicts. @lzchen please do a follow up if/as needed ;)

**Pull request merged**
