### PR TITLE
Delete sentence about using span name when faas.name is absent

### PR DESCRIPTION
**Pull request by tigrannajaryan**
As pointed out here https://github.com/open-telemetry/opentelemetry-specification/pull/888#discussion_r478866767
if faas.name is not set, the Instrumentation probably doesn't know the name
and thus the span name would most likely also not contain it.

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Review by Oberon00 — APPROVED** [review]

**Comment by bogdandrutu** [comment]
What about instrumentation that tries to not duplicate data?

**Comment by Oberon00** [comment]
faas.name is a resource attribute, so this should not be a concern.

**Comment by tigrannajaryan** [comment]
> What about instrumentation that tries to not duplicate data?

I am not sure if we ever made it a goal for Otel to minimize emitted data size. That is a very valid concern though, especially with more and more semantic conventions added. I don't know what's the solution to that, but we should probably discuss it in general, not specifically for just this one attribute.

**Comment by bogdandrutu** [comment]
I think I lost track of `faas` and what is on the client/function side. if this is a resource no brainier that we can send it always, I am interested more on the caller side how can we avoid having client Span name and faas attribute duplicate

**Comment by Oberon00** [comment]
We could avoid it by extending the span naming mechanism to refer to an existing attribute. But I think this is a minor concern.

**Comment by Oberon00** [comment]
But there is indeed a defect in these conventions: First the span name is specified under "General *Attributes*", second it says "Span `name` should be set to the function name being executed." which is unclear for outgoing FaaS.

But this is a separate issue from this PR.

**Comment by bogdandrutu** [comment]
Ok, I think what confuses me is the fact that this is in trace and not in resource semantic conventions. Can we clean that up in a future PR?

**Comment by Oberon00** [comment]
The faas.name is in the resource conventions, as it should be. But the trace semantic conventions reference it for the span name.

**Pull request merged**
