### PR TITLE
Remove resource reporting from zipkin exporter spec for now

### PR DESCRIPTION
**Pull request by anuraaga**
I had never noticed the word Resource here before. I think this is problematic since the overwhelming size / cardinality of resource will likely kill most zipkin deployments if attached to every span (zipkin data format does not have any mechanism for flattening these into a shared struct).

#823 discusses this but has been pushed to post-GA - I would recommend we also push Resource reporting for Zipkin to post-GA to coincide with that, or otherwise prioritize #823 (e.g., spec out a way for SDKs to allow filtering resource)

### CODE REVIEW

**Review by Oberon00 — APPROVED** [review]
Maybe it would make sense to a "MAY" for Resources and a short note describing the problem and suggesting to make it configurable.

**Comment by anuraaga** [comment]
@Oberon00 Yeah it makes sense but I'm a little worried about diverging configuration style. Especially if the setting is exposed as an environment variable, we could have inconsistency of the variable across languages. Do you think the recommendation makes sense with an added caveat of not being exposed as env var, which we usually spec in order to have consistency?

**Comment by Oberon00** [comment]
You are right, that is rather complicated. Let's leave this PR as-is then, and this configuration stuff can be done after GA.

**Comment by Oberon00** [comment]
Actually, we might want an issue for that, so it can be triaged.

**Comment by anuraaga** [comment]
Thanks - filed #1196

**Comment by jmacd** [comment]
This issue is remarkably similar to an issue in the metrics world facing most of the common exposition formats. I would like to see an OTel-wide solution. In Metrics we've discussed the outcome we'd like:
1. exporters w/o explicit resource supports will drop resources
2. users are expected to configure the resource->(label or attribute) translation they want
3. the OTel collector has (will have) a resource processor capable of moving resources into metric labels
The same should probably be said for trace exposition formats without resources.

**Comment by jmacd** [comment]
(I'm not sure we have a good GH issue capturing the above "issue", but it's been discussed in the context of Prometheus remote-write exporters recently.)

**Comment by anuraaga** [comment]
Oops lost track of this issue - is it ok to continue with it?

**Review by jmacd — APPROVED** [review]

**Comment by iNikem** [comment]
@jmacd As assignee, are you Ok with merging this or do we need more feedback?

**Comment by carlosalberto** [comment]
Overall LGTM - but as Jaeger Spans will keep this part, can we add a note here? something along "Resource as tags has been explicitly discarded for now, etc, etc".

**Review by carlosalberto — APPROVED** [review]

**Comment by jmacd** [comment]
I think we should merge this because #1196 has been filed.

**Pull request merged**
