### PR TITLE
Restore missing Link details

### PR DESCRIPTION
**Pull request by alexandrul**
This info was removed here: https://github.com/open-telemetry/opentelemetry-specification/pull/215/commits/055aedce2b9b94202190090f9cc95d13a5214106#diff-ee16351a427ae7ec4c060edb16018b9fL21

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please sign the CLA.

**Comment by jmacd** [comment]
I'm confused about what this actually means, for `Link` to be used concurrently. I suspect this language about Links being immutable dates to the time when `SpanData` was part of this specification. 

The way the spec reads now, Link is just a concept encapsulating:
```
#### Add Links

During the `Span` creation user MUST have the ability to record links to other `Span`s. Linked
`Span`s can be from the same or a different trace. See [Links
description](overview.md#links-between-spans).

A `Link` is defined by the following properties:

- (Required) `SpanContext` of the `Span` to link to.
- (Optional) One or more `Attribute`.

The `Link` SHOULD be an immutable type.
```

Then it says:

```
The Span creation API should provide:

- An API to record a single `Link` where the `Link` properties are passed as
  arguments. This MAY be called `AddLink`.
- An API to record a single `Link` whose attributes or attribute values are
  lazily constructed, with the intention of avoiding unnecessary work if a link
  is unused. If the language supports overloads then this SHOULD be called
  `AddLink` otherwise `AddLazyLink` MAY be considered. In some languages, it might
  be easier to defer `Link` or attribute creation entirely by providing a wrapping
  class or function that returns a `Link` or formatted attributes. When providing
  a wrapping class or function it SHOULD be named `LinkFormatter`.

Links SHOULD preserve the order in which they're set.
```

In the first bullet here, there's no need for a Link type, the span context and attributes are passed directly. In the second bullet here, `Link` is a lazy type--in which case I would not describe it as immutable.

So, I'd be happy to drop all language about Links being immutable, including the sentence above. 

One nit, if you're editing in here: "Links SHOULD preserve..." should be replaced by "Spans SHOULD preserve...". Links are not responsible for their ordering, Spans and/or Tracers should.

**Comment by jmacd** [comment]
I'd like someone to address this comment:
https://github.com/open-telemetry/opentelemetry-specification/pull/348#issuecomment-558314972

**Comment by carlosalberto** [comment]
So I'm wondering if there's *still* any scenario where modifying a `Link` (either by a lazy operation or updating its `SpanContext`/attributes) is a required thing at all (I thought that was a clear **no**, hence my previous approval).

**Pull request closed without merging**
