### PR TITLE
Fix attributes names in Google Cloud Logging mapping

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Vendor-specific attribute names must be prefixed
with reverse FQDN, see recommendation here
https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#recommendations-for-application-developers

### CODE REVIEW

**Review by kumoroku — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@jsuereth PTAL

**Comment by tigrannajaryan** [comment]
@jsuereth please have a look.

**Review by arminru — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@jsuereth PTAL.

**Comment by tigrannajaryan** [comment]
@jsuereth PTAL.

**Comment by bogdandrutu** [comment]
@jsuereth PTAL.

**Comment by tigrannajaryan** [comment]
I think this is safe to merge as it is merely in the Examples section. If later anyone from Google wants to fix it that's fine too.

**Pull request merged**
