### PR TITLE
Reduce entries in spec matrix to make it easier to read

### PR DESCRIPTION
**Pull request by cijothomas**
The spec compliance matrix for Metrics has a lot of entries, and I feel it is too detailed. This PR is proposing to collapse some of them - specifically this PR makes a single entry for "Support Counter instrument", which is implied to indicate everything related to Counter is supported, as opposed to a line entry for each of creation/add/add-with-attribute/value-validation etc. I don't see anything important enough for a user is "lost" with this condensed version.

If I get an okay for this direction, I can continue with doing same for other type of instruments as well. Overall, it'll make it easy for all to follow the matrix, without losing anything....

### CODE REVIEW

**Comment by carlosalberto** [comment]
Oops, sorry for missing this one. Let's poke the @open-telemetry/specs-metrics-approvers to confirm this is fine.

**Review by jsuereth — APPROVED** [review]
While this looses some fidelity, I agree this is more valuable for users.

We should try to bundle sets of requirements in this way to improve usefulness of the compliance matrix for readers.

**Review by jmacd — COMMENTED** [review]
I agree that the spec-matrix has become too large to be very useful, and that as the project matures we can collapse sections.

**Review by jmacd — APPROVED** [review]

**Comment by tsloughter** [comment]
The more detailed view can be useful to maintainers. But since there isn't a way collapse to make it easier for a user at the same time as keeping it I wouldn't really argue it should stay for that purpose.

**Review by tigrannajaryan — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Comment by cijothomas** [comment]
Thanks. Given the approvals, I'll spend some time to replicate this for other instruments as well and other places where it makes sense via small PRs.

**Pull request merged**
