### PR TITLE
feat: add attributes for cloud-native deployment

### LINKED ISSUE #3168: Semantic Convention for Deployments
Context
-----
I would like to propose a semantic convention for Cloud Native Deployments. This semantic convention will support the observability of deployments by enriching logs and DORA metrics with information about the application and/or microservices under deployment. Furthermore, traces could also be augmented with this data gaining visibility in all the steps the deployment goes through and pinpointing root causes of failure.
 
 
Proposed Attributes
----

 Deployments can have one or more applications. Each application comprises one or more processes, called [Workload](https://kubernetes.io/docs/concepts/workloads/) in K8s terminology. Furthermore, deployments usually also carry additional tasks that set the stage up to be able to serve the newly deployed application(s).
This issue proposes to track `name`, `version`, and `status` attributes for Application(s), Workload(s), and Task(s)
 
Please take a look at #3169 for a more comprehensive description.
 
 
Additional Info
------
 
We started implementing this in [Keptn](https://github.com/keptn/lifecycle-toolkit), an incubating CNCF project. An example of the usage of this data is available here: https://github.com/keptn-sandbox/klt-on-k3s-with-argocd

### PR DESCRIPTION
**Pull request by thisthat**
Fixes #3168

## Changes

This PR introduces semantic conventions for Cloud Native Deployments.

## Related issues 

- #3168

### CODE REVIEW

**Comment by thisthat** [comment]
Hey @carlosalberto, do you have some free cycles to look into this PR? :)

**Comment by dyladan** [comment]
This is not stale

**Comment by carlosalberto** [comment]
cc @open-telemetry/specs-logs-approvers

**Comment by thisthat** [comment]
ping to remove the stale label

**Comment by dyladan** [comment]
This is not stale

**Comment by trask** [comment]
hey @thisthat!

can you compare with (any) existing ECS conventions? (see https://github.com/open-telemetry/oteps/pull/222, #3408, and #3409 for context)

also, I think we can (and are trying to) share yaml definitions across signals now, so I think you can have a single yaml definition of the attributes now (see http for an example)

**Comment by thisthat** [comment]
Hey @trask, thanks for the pointers! I'll have a look at the ECS conventions and check for any overlap 👍

**Comment by dyladan** [comment]
I did have a look and didn't find any ECS attributes which map well to this. The closest are [package](https://www.elastic.co/guide/en/ecs/current/ecs-package.html), which could describe a built artifact to be deployed, and [service](https://www.elastic.co/guide/en/ecs/current/ecs-service.html), which could describe the application being deployed. 

The proposed conventions here don't really map well to ECS service fields as they are application level. I did not find any application level fields in ECS. Further, otel has typically used the service fields to describe the service being instrumented, but the service here is acting on a different service and we have no real way distinguish between the service instrumented and the service deployed.

Package might work well in a CI/CD context, but doesn't map well to any of the proposed fields here. This proposal seems more to do with deploying workloads rather than the actual build step.

---

There are [orchestrator](https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html) fields which seem promising for describing the entity actually scheduling the workload, but again I was unable to find a field describing the workload being orchestrated.

**Comment by trask** [comment]
@AlexanderWert @ruflin can you comment on whether you see any conflicts with adding `deployment.*` attributes?

**Comment by ruflin** [comment]
Looking into ECS fields to be used I stumbled over the same fields as @dyladan but couldn't see a direct mapping. @felixbarny What is your team using for this at the moment?

One general thing I stumbled over is the term application vs service. @thisthat What is for you the difference between the two? I think if we start to use both, we must have a really good descriptions for users that pick it up to know which one to use in which scenario. 

Overall, I definitively see value in being able to describe a deployment.

**Comment by felixbarny** [comment]
> @felixbarny What is your team using for this at the moment?

I don't think we're tracking any metadata about deployments or "applications", just services.

> One general thing I stumbled over is the term application vs service. @thisthat What is for you the difference between the two? I think if we start to use both, we must have a really good descriptions for users that pick it up to know which one to use in which scenario.

++

**Comment by reyang** [comment]
@thisthat heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

**Comment by ChrsMark** [comment]
@thisthat hey! Could you provide some more information/examples of how the schema you are adding will be used in real world scenarios for collectors like in Kubernetes environments?

From k8s docs the [workload](https://kubernetes.io/docs/concepts/workloads/) can be a Deployement, StatefulSet, Daemonset or Job/Cronjob. Would this information be mapped somehow on the schema you provide? If yes, could you provide an example of how we fill the proposed schema fields from the actual k8s Resource?

What I'm trying to understand here is how an agent/collector would leverage those values to report data collected for Pods, Containers or any other kind of Resource.

BTW, [orchestrator](https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html) schema from ECS includes the `orchestrator.resource.*` fields that might be familiar here? For example `[orchestrator.resource.name](https://www.elastic.co/guide/en/ecs/current/ecs-orchestrator.html#field-orchestrator-resource-name)`.

Sorry if I miss anything here, and happy to elaborate more if needed :).

cc: @ruflin @AlexanderWert

**Review by jsuereth — CHANGES_REQUESTED** [review]
Please move this to https://github.com/open-telemetry/semantic-conventions

**Comment by thisthat** [comment]
Thanks all for looking into this PR. I will provide a new PR in the new repo and tag all the people here so we can continue the discussion over there. 

@ruflin

> One general thing I stumbled over is the term application vs service. @thisthat What is for you the difference between the two? I think if we start to use both, we must have a really good descriptions for users that pick it up to know which one to use in which scenario.

I used the term *service* to refer to the general notion of *microservice*. Maybe a better name could be *process*.
The term *application* describes the group of *services* that belongs together and form an application.
Basically, if you look at the [K8s recommended labels](https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/#labels), the *service* is the `app.kubernetes.io/name` and the *application* is `app.kubernetes.io/part-of`. This should also answer your question @ChrsMark

**Comment by arminru** [comment]
This PR was moved to https://github.com/open-telemetry/semantic-conventions/pull/24.

**Pull request closed without merging**
