### PR TITLE
Rename two JVM runtime metrics

### PR DESCRIPTION
**Pull request by trask**
## Changes

Renames 2 JVM runtime metrics:
* `process.runtime.jvm.cpu.utilization` --> `process.runtime.jvm.cpu.recent_utilization`
* `process.runtime.jvm.system.cpu.utilization` --> `process.runtime.jvm.system.cpu.recent_utilization`

This is to make clear that these are gauges (utilization for "some" recent period of time) as opposed to measures of utilization since the last metric export/scrape.

EDIT: maybe `process.runtime.jvm.cpu.load` and `process.runtime.jvm.system.cpu.load` would also be good? (and matches the MBean attribute names that these are sourced from)

### CODE REVIEW

**Review by jack-berg — APPROVED** [review]

**Comment by carlosalberto** [comment]
I'm guessing this is done to simply be more descriptive - is that it, or is there another reason?

**Comment by trask** [comment]
> I'm guessing this is done to simply be more descriptive - is that it, or is there another reason?

sorry, I added reason into description above now.

also, as I was doing that, I revisited and now wondering if these might be better:

* `process.runtime.jvm.cpu.load`
* `process.runtime.jvm.system.cpu.load`

I think this similarly avoids the issue about "utilization since last export", and they also match the MBean attribute names that they're sourced from.

**Comment by reyang** [comment]
@trask heads up - most likely this PR will be closed, and we'll ask you to resubmit the PR in a new repo, please refer to https://github.com/open-telemetry/opentelemetry-specification/pull/3474#issuecomment-1539386505.

**Review by jsuereth — CHANGES_REQUESTED** [review]
Please move this PR to https://github.com/open-telemetry/semantic-conventions

**Comment by trask** [comment]
Closing in favor of issues: https://github.com/open-telemetry/semantic-conventions/issues/42 and https://github.com/open-telemetry/semantic-conventions/issues/41

**Pull request closed without merging**
