### PR TITLE
Update api.md

### PR DESCRIPTION
**Pull request by aman-raza**
Fixes #

## Changes

Removed the optional tag from the "version" param and the "required" tag from name param.

### CODE REVIEW

**Comment by yurishkuro** [comment]
what is the motivation for this change?

**Comment by aman-raza** [comment]
> what is the motivation for this change?

Both the name and version is required by the traceprovider
currently it is optional

**Comment by Oberon00** [comment]
> Both the name and version is required by the traceprovider

Which language are you talking about?

**Comment by aman-raza** [comment]
> > Both the name and version is required by the traceprovider
> 
> Which language are you talking about?

php

**Comment by Oberon00** [comment]
I think this is an issue with PHP then. This repository is a specification not a documentation. That is, it states how the implementations *should* be. It is not (primarily) a user manual.

**Comment by aman-raza** [comment]
> I think this is an issue with PHP then. This repository is a specification not a documentation. That is, it states how the implementations _should_ be. It is not (primarily) a user manual.

ohh so I have to look for the issue in .php then, got it

**Pull request closed without merging**
