### PR TITLE
Prometheus histogram bucket metric ends in _bucket

### PR DESCRIPTION
**Pull request by dashpole**
I realized when opening https://github.com/open-telemetry/opentelemetry-swift/issues/355 that the current prometheus spec for histograms is incorrect (though almost all implementations of prometheus exporters is correct).

From the [prometheus spec](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md#histograms-and-summaries):

> Each bucket count of a histogram named x is given as a separate sample line with the name x_bucket and a label {le="y"} (where y is the upper bound of the bucket).

From the [OpenMetrics spec](https://github.com/OpenObservability/OpenMetrics/blob/main/specification/OpenMetrics.md#histogram-1):

> The MetricPoint's Bucket Values Sample MetricNames MUST have the suffix "_bucket".

This corrects our specification to be in-line with prometheus and OM specs

### CODE REVIEW

**Comment by dashpole** [comment]
cc @gouthamve @jmacd

**Review by gouthamve — APPROVED** [review]
LGTM

**Comment by dashpole** [comment]
cc @open-telemetry/wg-prometheus

**Review by jack-berg — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Comment by dashpole** [comment]
I believe this can be merged.

**Review by Aneurysm9 — APPROVED** [review]

**Pull request merged**
