### PR TITLE
Introduce EKS cluster semantic conventions

### PR DESCRIPTION
**Pull request by rakyll**
This change is a follow-up to https://github.com/open-telemetry/opentelemetry-specification/issues/1098 and introduces EKS specific semantic conventions.

### CODE REVIEW

**Review by arminru — APPROVED** [review]
I'm not familiar with EKS but this looks reasonable to me since `k8s.cluster.name` will likely not be sufficient to uniquely identify an EKS cluster.

@rakyll Please also add the new file/convention to the TOC in `specification/resource/semantic_conventions/cloud_provider/aws/README.md`.

**Comment by rakyll** [comment]
Done, @arminru. PTAL.

**Review by anuraaga — APPROVED** [review]

**Comment by pmm-sumo** [comment]
BTW, it might be somewhat redundant, but perhaps it would be good to have `aws.eks.cluster.name` as well? (I believe it can be extracted from ARN)

**Comment by rakyll** [comment]
Conflict is resolved, this is good to merge.

**Review by carlosalberto — APPROVED** [review]

**Pull request merged**
