### PR TITLE
Clarify that Events and Log Records are conceptually the same thing

### PR DESCRIPTION
**Pull request by tigrannajaryan**
I get this question a lot. This clarifies that events and log records
are different names of the same concept (from Otel perspective).

This was discussed verbally many times and I believe it was also
in my initial logs proposal but got lost somewhere in the process.

This also fixes the TBD link in the spec that was supposed to point
to this explanation.

### CODE REVIEW

**Review by yurishkuro — COMMENTED** [review]
Hm, not sure if this is a fair comparison. 

First, you're quoting a definition of a "log file", not a "log". A log is just a more abstract notion of a log file, i.e. a Kafka topic's partition is also a "log".

Second, log != event because of difference in cardinality. More accurately, log is a sequence of events.

Finally, I think it is worth addressing the difference in meaning between "logs" as in "metrics, traces, and logs", and log as an abstract notion of sequentially written events. I don't think OTEL is aiming to deal with the latter, we're mostly talking about _application logs_, which some people differentiate from business events, and change management events. In other words, we are talking about logs as a telemetry signal, not logs as a transport mechanism.

**Comment by tigrannajaryan** [comment]
@yurishkuro you are right, if we look into the more nuanced definition of the log vs log record vs event. 

However, the confusion I often see is that some people think that events are an entirely new concept that somehow requires a separate treatment in OpenTelemetry. I am trying to reduce this particular confusion.

I updated the wording to make it clearer that I am equating Log Records and Events, which is a more fair comparison. Note: I am using Events in the sense that Wikipedia uses them in the quote I added in the PR or [Windows Events system](https://en.wikipedia.org/wiki/Event_Viewer) use them. They are nothing but log records from this perspective (also known as "events", "event logs", and sometimes plainly "logs").

Unfortunately Wikipedia has no definition of Log, so I had to link to Log File as he best approximation, since it serves my purpose anyway because it clearly talks about events.

**Review by yurishkuro — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Review by kumoroku — APPROVED** [review]

**Comment by reyang** [comment]
We need to clarify if `Span.AddEvent` is a logging API or not (I believe it is not).

**Review by jmacd — APPROVED** [review]

**Comment by jmacd** [comment]
> We need to clarify if Span.AddEvent is a logging API or not (I believe it is not).

I read the text of this PR to say that `AddEvent` is a logging API.

**Review by iNikem — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
According to glossary.md:
>**Embedded Log**
>Log Records embedded inside a Span object, in the Events list.

This definition probably needs to be refined. But semantically it definitely is a log record. At one point I wanted to make sure the data models are aligned but it did not get enough traction at the time: https://github.com/open-telemetry/opentelemetry-specification/issues/622

**Comment by kenfinnigan** [comment]
I may be misunderstanding the intent, but I see logs being used today as being different from an event both in their intent and their data modeling.

Having a log, as an example, with "ERROR", a timestamp, and an arbitrary message is very different from a structured event, that could happen to be written to a log.

Where does OpenTelemetry believe "logs" fit in terms of https://charity.wtf/2019/02/05/logs-vs-structured-events/ ?

**Comment by tigrannajaryan** [comment]
> I may be misunderstanding the intent, but I see logs being used today as being different from an event both in their intent and their data modeling.
> 
> Having a log, as an example, with "ERROR", a timestamp, and an arbitrary message is very different from a structured event, that could happen to be written to a log.

It is not clear to me what is "very different" from OpenTelemetry perspective. Both are possible to represent and process using existing Otel log data model. 

> Where does OpenTelemetry believe "logs" fit in terms of https://charity.wtf/2019/02/05/logs-vs-structured-events/ ?

This PR attempts to describe what OpenTelemetry believes. Any real or mythical differences between "logs" and "structured events" don't matter for OpenTelemetry. We are not in the business that requires differentiating the two.

**Review by reyang — APPROVED** [review]
LGTM.

**Pull request merged**
