### PR TITLE
Add semantic conventions for nginx metrics

### PR DESCRIPTION
**Pull request by nslaughter**
## Changes

- Add nginx metrics semantic conventions.

### CODE REVIEW

**Comment by carlosalberto** [comment]
So the `nginx.requests` can easily be abstracted as `proxy.requests` or similar.

About the other ones, I'm not entirely sure it's possible to _easily_ abstract them - is there a clear, common distinction between what is considered an accepted/handled/current connection among different proxies/servers? Maybe there is, but maybe not. In that case, do we _try_ to 'unify't them? Not really sure that's a way I'd go.

**Comment by carlosalberto** [comment]
So the `nginx.requests` can easily be abstracted as `proxy.requests` or similar.

About the other ones, I'm not entirely sure it's possible to _easily_ abstract them - is there a clear, common distinction between what is considered an accepted/handled/current connection among different proxies/servers? Maybe there is, but maybe not. In that case, do we _try_ to 'unify't them? Not really sure that's a way I'd go.

**Comment by nslaughter** [comment]
Thank you for the feedback @MrAlias and @carlosalberto. I've taken a closer look and I'd like to get more specific feedback regarding the approach. The questions are at the end.

## What metrics are commonly supported by proxies?

I looked at stats for HAProxy and Envoy to get a broader idea of commonly computed metrics as a reference for what OTEL users may require. 

Here's a table of how like metrics are provided...

| nginx                 | envoy                         | haproxy                              |
|-----------------------|-------------------------------|--------------------------------------|
| .requests             | .http.downstream_rq_completed | .Sessions.Frontend.Cum.HTTP_requests |
| .connections_accepted | .http.downstream_cx_total     | .Sessions.Frontend.Cum.Connections   |
| .connections_handled  | ?                             | ?                                    |
| .connections_current  | .http.downstream_cx_active    | .Backend.Cur.Connections             |

The breakdown of current connections by state is apparently not supported by Envoy or HAProxy. I also noted that the equivalent of .connections_handled could be calculated from stats provided by the other two.

## How could we make the semantic conventions more useful and general?

After reviewing the feedback I see that `nginx.requests` could be `otel.http.server.active_requests`. And `nginx.connections_current` could be `otel.system.network.connections`. That makes sense to me assuming it's appropriate to use system metrics for services.

Does the commonality of `.connections_accepted` as a cumulative metric suggest that we should also support that in the conventions?

**Comment by carlosalberto** [comment]
Hey @nslaughter - thanks for the update!

> The breakdown of current connections by state is apparently not supported by Envoy or HAProxy

IMHO we should not try too hard to unify metrics - instead, add metrics for the most common cases, and let specific components add their very-specific ones. In this case we could perhaps define total/active connections as common metrics, and have nginx define an additional one for its `.connections_handled`?

(Btw, a general metric for requests is fine - probably a new one, as the existing one is for **active** requests, whereas envoy's metric seems to be for **completed** ones)

Opinion @MrAlias ?

**Comment by nslaughter** [comment]
Thanks for the help, @tedsuo.

Regarding... 
> * `nginx.connections_current` should map to `http.server.active_requests` not `system.network.connections`

Mapping something called `connections` to something called `requests` is confusing to me. My understanding is that they would map under the original HTTP model, but with persistent connections, pipelining, and concurrency beyond HTTP 1.1 we can only expect the `active_connections <= active_requests`. That said, I'm neither expert in networking nor these conventions.

> * small fyi, we don't currently use `otel` as a namespace prefix.

Thanks for pointing that out. I introduced that confusion hoping to clarify the distinction when side-by-side with something called `nginx` otherwise that's the namespace I would have expected as it is in collector-contrib. Will fix it.

> One larger point: NGINX is currently adding native integration of OTel. I will notify them and make sure we get their input; we should avoid a situation where we define something in the spec which doesn't match what they are actually building. :)

Thanks for the awareness and comms on this. Much appreciated.

**Comment by carlosalberto** [comment]
@tedsuo Any reason to not go with `proxy.*` instead? Just trying to be on the conservative side (and avoid collusions 😄 ) 
 
 Not a string opinion, just considering our options.

**Comment by gramidt** [comment]
Hi All - 

This PR was just brought to my attention, and I wanted to let you know that it's being circulated to the corresponding NGINX teams within F5.

**Comment by carlosalberto** [comment]
Thanks @gramidt !

Other than that part of the review, circling back, I'd like to propose:

1. Metrics are dead obvious (e.g. requests) exist under `proxy.*`, e.g. `proxy.requests`.
2. Metrics for operations that are NOT dead obvious go under `proxy.<component>.metric`, e.g. `proxy.nginx.connections.handled`.
3. We _eventually_ merge some of the ones in 2 as common metrics.

The reason for this is that trying to _audit_ all new metrics may severely slow us down overall - and as they say, "perfect is the enemy of good" (or done).

**Comment by nslaughter** [comment]
Closing this for the time... Will revisit this with a proposal reflecting some feedback so concensus can coalesce -> then move from towards a PR.

**Pull request closed without merging**
