### PR TITLE
make maxExportBatchSize an optional part of an implementation

### PR DESCRIPTION
**Pull request by tsloughter**
Implementations where the batches to be exported are best left where they are after finishing, instead of copying, can not reasonably support a batch size smaller than the `maxQueueSize`, so this change makes it an optional configuration to support..

With the Erlang implementation the exporters are passed a reference to a table that is the queue, up to `maxQueueSize`, to support a `maxExportBatchSize` would require copying from the table to the process heap, doubling the memory usage.

### CODE REVIEW

**Comment by SergeyKanzhelev** [comment]
@tsloughter what's the motivation for this change? Can you please add a description?

**Comment by tsloughter** [comment]
Woops, sorry about that, updating the PR description

**Comment by SergeyKanzhelev** [comment]
@tsloughter so in Erlang implementation Exporters has no guarantees on how big of a batch will be passed by processor for the export? If Exporter has a limit on how many items it can send at a time - will it be required to do extra batch itself? So it will still imply some manipulations of batches. Perhaps I'm missing something.

**Comment by tsloughter** [comment]
@SergeyKanzhelev the size is still limited by `maxQueueSize`. That is the max size of the table that finished spans are stored.

If the exporter can only send N spans in a batch it will have to iterate over the table up to N. It makes sense to provide functions for that in the Erlang impl but not to copy them before calling the exporter.

And since the maxExportBatchSize isn't tied to the exporter itself but a configuration for the batch processor that calls the exporter won't the exporter have to make sure it batches at the right size anyway, since it guaranteed that the maxExportBatchSize is set to what the service that is being exported to supports? Same goes for the fact that exporters are chainable and may have different allowed batch sizes.

**Comment by bogdandrutu** [comment]
@tsloughter what about implementing a "SpanExporter" that from a larger batch can split that into smaller batches.

BatchSpanProcessor -> BatchSplitterExporter -> BackendExporter?

**Comment by SergeyKanzhelev** [comment]
@tsloughter sorry fro delayed response. +1 to what @bogdandrutu asked. Plus - would it be possible to implement passing batches as a link to larger array with indexes in this case? 

My big concern over not allowing specifying batch sizes and moving this logic to the exporter - there will be a situations of partial success in spans delivery. Which we do not account for in this design. I believe the idea is that exporter may configure it's batch processor the way it needs to. And processor will handle retries.

**Comment by tsloughter** [comment]
Yes, @bogdandrutu 's idea might work. I hadn't thought about retries. I need to work on exporters some more for the language agnostic changes and some of it is still unclear to me what is expected (like chaining). I'll close this with the intention of a new PR eventually that works off @bogdandrutu 's idea.

**Pull request closed without merging**
