### PR TITLE
Metric units should use UCUM case sensitive variant

### PR DESCRIPTION
**Pull request by jack-berg**
Related to #705.

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
Although not introduced by this PR, I just want to call out that we might run into trouble with the current spec:

https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-unit

image

image

**Review by jmacd — APPROVED** [review]

**Comment by jack-berg** [comment]
@reyang I don't understand - single quote is a valid ascii character, no?

**Comment by reyang** [comment]
> @reyang I don't understand - single quote is a valid ascii character, no?

"single quote is a valid ascii character" - right. The problem I'm seeing - UCUM c/s doesn't say anything about the allowed characters, we don't know if we'll see non-ASCII chars.

**Comment by MrAlias** [comment]
> Although not introduced by this PR, I just want to call out that we might run into trouble with the current spec:
> 
> https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/metrics/api.md#instrument-unit
> 
> image
> 
> image

Aren't these just two single quote characters (ASCII code 39)?

**Comment by reyang** [comment]
> 

Ah, I see, that removes the concern. Thanks!

**Review by MrAlias — APPROVED** [review]

**Pull request merged**
