### PR TITLE
Merge OTEPs into the Specification.

### PR DESCRIPTION
**Pull request by carlosalberto**
Latest attempt to merge the OTEPs repo into the Specification:

* OTEPs will live under the `oteps` directory, next to `specification` one.
* History has been kept.
* Updated @codeboten email from his previous defunct value (preventing CLA check).

Additionally, additional lint fixes in order to merge this:

* Removed dead links, e.g. links to now removed Lightstep documentation.
* Updated links that point to the Specification (our current lint prefers *local*, rather than absolute addresses).
* Updated links for components that have been moved around, e.g. semantic conventions and the protocol.

Follow-ups:

* Clarification on the README & each OTEP that these are proposal of intent, not actual specification instructions.
* Normative language usage clarification.
* How to assign OTEP numbers (we cannot rely on PR number, as we did in the OTEPs repository).
* Move issues from the OTEPs repository (to either the Specification or semantic conventions).
* Archive the OTEPs repository (it should still be reachable, for historical purposes).

### CODE REVIEW

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
:shipit:

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
>How to assign OTEP numbers (we cannot rely on PR number, as we did in the OTEPs repository).

Why not? Because the numbers are too big? 4 digits seems ok to me and we are likely going to end up with a maximum of 5 digits in the lifetime of this repo which is perhaps a bit much but still not terrible.

**Review by arminru — APPROVED** [review]

**Comment by carlosalberto** [comment]
> Why not? Because the numbers are too big? 4 digits seems ok to me and we are likely going to end up with a maximum of 5 digits in the lifetime of this repo which is perhaps a bit much but still not terrible.

I wouldn't be completely opposed to it, as long as we accept the trade-off ;)

**Comment by carlosalberto** [comment]
Merging today to avoid any conflict/issue. Will follow up with pending tasks as part of #4284

**Pull request merged**
