### PR TITLE
[chore] Fix wrong metric type in OTel to Prom compatibility section.

### PR DESCRIPTION
**Pull request by kovrus**
Fix the wrong metric type in the OTel to Prometheus compatibility section.

### CODE REVIEW

**Review by reyang — APPROVED** [review]
LGTM.

**Comment by reyang** [comment]
@kovrus thanks for the catch!

**Review by MrAlias — APPROVED** [review]

**Comment by carlosalberto** [comment]
cc @dashpole

**Review by dashpole — APPROVED** [review]
Thanks for catching this!

**Pull request merged**
