### PR TITLE
add metrics to replace metrics with `direction`

### PR DESCRIPTION
**Pull request by codeboten**
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/2589

## Changes

This PR looks to address the concerns voiced in #2589. It adds new metrics that include the direction in their names, and marks existing metrics as deprecated.

A few questions I have in mind:
1. Are there other dimensions that may also need to be addressed? I'm not sure if it makes sense to have a `protocol` dimension for network metrics that ends up combining UDP and TCP as one is stateless and the other stateful.
2. Can the change in this PR be added in a schema to assist end users?

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
I am not a metrics expert and don't have an opinion on whether this is the right approach, however if we go ahead with this I would like to be able to model this change in the Schema. We need to add a new type of transform in the Schema file, essentially an ability to split a metric into multiple metrics by eliminating a dimension.

I will wait a bit until we get approvals on this PR and if we are going ahead with it I will make the corresponding proposal to add the new transform to Schemas.

Also, @codeboten can you clarify how this impacts the Collector? Do we already emit these metrics in the Collector? If yes, then we are going to change Collector implementation too as a result of this PR.

**Comment by codeboten** [comment]
> Also, @codeboten can you clarify how this impacts the Collector? Do we already emit these metrics in the Collector? If yes, then we are going to change Collector implementation too as a result of this PR.

@tigrannajaryan yes this will impact the hostmetrics receiver. If this change goes it, I will go ahead and make the changes as needed.

Any thoughts on whether a similar change to this one should be proposed around separating `protocol`?

**Review by jack-berg — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> Any thoughts on whether a similar change to this one should be proposed around separating `protocol`?

it seems like `protocol` is a valid dimension. I think aggregation of `system.network.connections` by `protocol` is meaningful. You can sum and get the total number of connections regardless of the protocol.

**Comment by tigrannajaryan** [comment]
@dmitryax please check if this change also requires corresponding changes to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter

**Comment by codeboten** [comment]
> it seems like `protocol` is a valid dimension. I think aggregation of `system.network.connections` by `protocol` is meaningful. You can sum and get the total number of connections regardless of the protocol.

This is true, but aggregating protocols over `state` would be meaningless, as it would exclude UDP

**Comment by tigrannajaryan** [comment]
> This is true, but aggregating protocols over `state` would be meaningless, as it would exclude UDP. If you wanted to get all connections with the state `open`, you may think you're getting all connections, but really you'd only see tcp connections.

It seems to be even worse than that.

The `state` is barely defined in our spec, it is just a link to Wikipedia article about tcp which is not nearly enough precision for our spec. Depending on how the `state` is properly defined it may or may not be meaningful to aggregate across (`open` is not a valid value even for tcp connections). It probably warrants its own PR.

**Review by trask — APPROVED** [review]

**Comment by dmitryax** [comment]
> @dmitryax please check if this change also requires corresponding changes to https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter/signalfxexporter

Yes, we need to add another translation rule to combine `system.disk.io.read` and `system.disk.io.write` into `system.disk.io.total`. That shouldn't be complicated

**Comment by bertysentry** [comment]
Is there somewhere an active discussion on this topic? I'd like to see some arguments backing the proposed change. Issue #2589 is merely a question from @tigrannajaryan.

**Comment by carlosalberto** [comment]
@bertysentry We can discuss them tomorrow in the Spec call, which happens at 8am Pacific. Would you be interested in joining?

**Review by jmacd — APPROVED** [review]
I support this change to the general semantic conventions provided the schema translation formats and tools are updated to handle conversion. 

My opinion has been influenced by the widespread practice of keeping bidirectional metrics separate, though it does seem like a new semantic convention is emerging (e.g., the use of ".read" and ".write" suffixes).

**Comment by carlosalberto** [comment]
@bertysentry We have it in our Google Calendar, and the call itself happens through Zoom ;)  See https://calendar.google.com/calendar/u/0/r?cid=Z29vZ2xlLmNvbV9iNzllM2U5MGo3YmJzYTJuMnA1YW41bGY2MEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t

**Comment by reyang** [comment]
Discussed during the Jun 28, 2022 Specification SIG Meeting, folks agreed to go with this direction.

**Comment by tigrannajaryan** [comment]
@codeboten now that https://github.com/open-telemetry/opentelemetry-specification/pull/2653 is merged can you please add a schema file 1.13 with the transformation that describes this PR? We need to publish it with the next spec release.

**Pull request merged**
