### PR TITLE
Remove local stubs of semantic conventions.  

### PR DESCRIPTION
**Pull request by jsuereth**
- Remove semantic convention stubs
- Update all links to point at new repo.
- Update CODEOWNERS for new areas of responsibility for semconv approvers

Note: There's a few things that need to updated as part of further cleanup.

Replaces #3667

### CODE REVIEW

**Review by trask — APPROVED** [review]

**Review by pyohannes — APPROVED** [review]

**Review by arminru — APPROVED** [review]
cc @chalin - to make sure we don't break the website with this 🙂

**Review by carlosalberto — APPROVED** [review]

**Comment by carlosalberto** [comment]
Thanks! So much needed!

**Review by reyang — APPROVED** [review]

**Comment by reyang** [comment]
> cc @chalin - to make sure we don't break the website with this 🙂

@chalin FYI to avoid running into reciprocating merge conflicts, I merged the PR as editorial changes. If there is anything we need to fix, we can quickly do it in follow up PRs.

**Comment by chalin** [comment]
Looking into potential breakages on the website side of things now.

**Comment by chalin** [comment]
Oh, this is in v1.26.0! So all is good! ✨

**Pull request merged**
