### PR TITLE
Add 'type' to all groups

### PR DESCRIPTION
**Pull request by CleanCut**
Adds a `type` to every group to resolve the build tools' unsilenceable warning mentioned in https://github.com/open-telemetry/build-tools/pull/109

## Changes

I added a `type` field to every group that was missing one. Since I didn't know what value to put, I guessed `resource` for the ones in the `resource` subdirectory, and left all the rest to `span` since that's what they were defaulting to.

This silences the warnings and results in zero differences in generated code in my testing.

Before this change (without https://github.com/open-telemetry/build-tools/pull/109#issuecomment-1194682078)

```
Using default SPAN type for semantic convention 'browser' @ line 5
Using default SPAN type for semantic convention 'cloud' @ line 5
Using default SPAN type for semantic convention 'aws.ecs' @ line 5
Using default SPAN type for semantic convention 'aws.eks' @ line 5
Using default SPAN type for semantic convention 'aws.log' @ line 5
Using default SPAN type for semantic convention 'container' @ line 5
Using default SPAN type for semantic convention 'deployment' @ line 5
Using default SPAN type for semantic convention 'device' @ line 5
Using default SPAN type for semantic convention 'faas_resource' @ line 5
Using default SPAN type for semantic convention 'host' @ line 5
Using default SPAN type for semantic convention 'k8s.cluster' @ line 5
Using default SPAN type for semantic convention 'k8s.node' @ line 5
Using default SPAN type for semantic convention 'k8s.namespace' @ line 5
Using default SPAN type for semantic convention 'k8s.pod' @ line 5
Using default SPAN type for semantic convention 'k8s.container' @ line 5
Using default SPAN type for semantic convention 'k8s.replicaset' @ line 5
Using default SPAN type for semantic convention 'k8s.deployment' @ line 5
Using default SPAN type for semantic convention 'k8s.statefulset' @ line 5
Using default SPAN type for semantic convention 'k8s.daemonset' @ line 5
Using default SPAN type for semantic convention 'k8s.job' @ line 5
Using default SPAN type for semantic convention 'k8s.cronjob' @ line 5
Using default SPAN type for semantic convention 'os' @ line 5
Using default SPAN type for semantic convention 'process' @ line 5
Using default SPAN type for semantic convention 'process.runtime' @ line 5
Using default SPAN type for semantic convention 'service' @ line 5
Using default SPAN type for semantic convention 'telemetry' @ line 5
Using default SPAN type for semantic convention 'webengine_resource' @ line 5
```

Also **before** this change (with https://github.com/open-telemetry/build-tools/pull/109#issuecomment-1194682078)

```
Please set the type for group 'browser' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'cloud' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'aws.ecs' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'aws.eks' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'aws.log' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'container' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'deployment' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'device' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'faas_resource' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'host' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.cluster' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.node' on line 13 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.namespace' on line 29 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.pod' on line 40 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.container' on line 56 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.replicaset' on line 76 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.deployment' on line 92 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.statefulset' on line 108 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.daemonset' on line 124 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.job' on line 140 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'k8s.cronjob' on line 156 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'os' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'process' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'process.runtime' on line 73 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'service' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'telemetry' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
Please set the type for group 'webengine_resource' on line 2 - defaulting to type 'span'. See https://github.com/open-telemetry/build-tools/blob/main/semantic-conventions/syntax.md#groups
```

After this change:

- (There is no no warning output afterwards)

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@CleanCut can you show in the PR description what was the warning? Ideally include before and after output to make it clear what is improved.

**Comment by CleanCut** [comment]
@tigrannajaryan ✅ Added. Note: There's no output afterwards (that's the whole point).

**Review by MovieStoreGuy — APPROVED** [review]
These changes make sense to me, I don't see any negative impact of this.

**Comment by MovieStoreGuy** [comment]
I also ask in future that instead of a screenshot, you add just the raw text since it makes it easier to grep for logs / errors in the code.

**Comment by CleanCut** [comment]
> I also ask in future that instead of a screenshot, you add just the raw text since it makes it easier to grep for logs / errors in the code.

Sure thing. ✅ Adjusted.

**Review by arminru — APPROVED** [review]
Thank you!

**Review by joaopgrassi — APPROVED** [review]
I'm working on generating code files from the conventions for .NET and I started noticing these warnings as well. Thanks for addressing them!

**Review by reyang — APPROVED** [review]

**Comment by CleanCut** [comment]
No problem! They've been bothering us for awhile.

**Pull request merged**
