### PR TITLE
Add .gitignore

### PR DESCRIPTION
**Pull request by iredelmeier**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please sign the CLA.

**Comment by iredelmeier** [comment]
Should be signed. Hopefully this comment re-triggers the CLA check...

**Comment by bogdandrutu** [comment]
For me a close/reopen worked in other cases. Please consider to reopen the PR if you are sure you signed. Also you need to make sure you have the email setup in your github account and you signed the PR with your email.

**Comment by iredelmeier** [comment]
Commenting again because I've updated my CLA roles. 🤞

**Comment by iredelmeier** [comment]
Interesting. Looks like you specifically need the "contributing employee" role; "organization manager" without it won't work.

**Comment by bogdandrutu** [comment]
So all this effort for an empty file? Is this expected?

**Comment by bogdandrutu** [comment]
Just want to confirm that you want to submit an empty file correct?

**Comment by iredelmeier** [comment]
Yes.

**Pull request merged**
