### PR TITLE
Framework to support W3C test-driven specification

### LINKED ISSUE #1210: Make it possible to automatically list all specification requirements
This is the original content of this issue:

*What are you trying to achieve?*
I am trying to quickly make a list of specification requirements in order to check the specification compliance of a particular implementation.

*What did you expect to see?*
I was expecting to easily find all the requirements that make up the specification.

*Additional context.*
I have been reading some parts of the specification and found that the usage of [RFC 2119](https://tools.ietf.org/html/rfc2119) keywords is sometimes inconsistent, some hard requirements are not specified with MUST, some optional requirements are not specified with SHOULD/MAY. Instead, some requirements are written using other terms that have the same meaning but not the exact syntax of RFC 2119. This makes it impossible to simply search for these keywords in the specification in order to find all the precise requirements that make up the document.

@jmacd [requested](https://github.com/open-telemetry/opentelemetry-specification/pull/2003#issuecomment-942569789) an issue to be filed. I prefer to reuse this one to minimize the amount of issues :+1:

### Motivation for this change

The spec is hard to understand because it is written in an inconsistently-applied formal language. Here are some examples:

- [This is a "Recommendations" section where MUST and SHOULD appear both](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#recommendations-for-opentelemetry-authors)
- [This section states that a name SHOULD SHOULD NOT coincide with namespaces](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/attribute-naming.md#attribute-naming)
- [This section uses the terms "this is required for..." instead of using MUST](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attributes)
- [This section includes conditional requirements. It is hard to find which requirements an implementation has to fulfill if it requires finding any conditions in the specification first](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/common/common.md#attribute-limits)
- [This section uses may in lower case](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/opencensus.md#opencensus-binary-context)

When implementing OpenTelemetry it is very hard to know what has to be implemented because there is no clear listing of all requirements. If the specifcation is written in the way intended in this PR it will be possible to generate automatically a list of every requirement and condition that the specification states.

It is also much easier to check that the specification is correct if we only need to check a list of well defined sections. Some checks (like having a RFC 2119 keyword, for example) can even be automated.

It is also easier to communicate between OpenTelemetry participants if the requirements are clearly identifiable, this approach uses markdown headings so that each requirement will have its own URL so that they can be used as reference in Slack, email, etc.

### Steps

Fixing this issue will require a big change, because it means reformatting every document that has been written to this moment, so it would be convenient to separate this into smaller steps:

- [ ] Merge the [specification-writing guidelines](https://github.com/open-telemetry/opentelemetry-specification/pull/2003/files#diff-0219b1a94eb4180d8dfca3754feb1363702cbef0d41f0672c7dce85df96bfa2c)
- [ ] Update the specification document status states to manage the transition
- [ ] Merge the scripts that generate the JSON files from the specification markdown files
- [ ] Reformat common/attribute-naming.md
- [ ] Reformat common/common.md
- [ ] Reformat sdk-configuration.md
- [ ] Reformat context/api-propagators.md
- [ ] Reformat context/context.md
- [ ] Reformat overview.md
- [ ] Reformat protocol/exporter.md
- [ ] Reformat protocol/otlp.md
- [ ] Reformat protocol/design-goals.md
- [ ] Reformat protocol/requirements.md
- [ ] Reformat performance-benchmark.md
- [ ] Reformat vendors.md
- [ ] Reformat logs/overview.md
- [ ] Reformat logs/data-model.md
- [ ] Reformat sdk-environment-variables.md
- [ ] Reformat compatibility/openmetrics.md
- [ ] Reformat compatibility/opentracing.md
- [ ] Reformat compatibility/opencensus.md
- [ ] Reformat resource/sdk.md
- [ ] Reformat resource/semantic_conventions/device.md
- [ ] Reformat resource/semantic_conventions/cloud_provider/aws/logs.md
- [ ] Reformat resource/semantic_conventions/cloud_provider/aws/README.md
- [ ] Reformat resource/semantic_conventions/cloud_provider/aws/eks.md
- [ ] Reformat resource/semantic_conventions/cloud_provider/aws/ecs.md
- [ ] Reformat resource/semantic_conventions/webengine.md
- [ ] Reformat resource/semantic_conventions/os.md
- [ ] Reformat resource/semantic_conventions/README.md
- [ ] Reformat resource/semantic_conventions/deployment_environment.md
- [ ] Reformat resource/semantic_conventions/k8s.md
- [ ] Reformat resource/semantic_conventions/host.md
- [ ] Reformat resource/semantic_conventions/process.md
- [ ] Reformat resource/semantic_conventions/faas.md
- [ ] Reformat resource/semantic_conventions/container.md
- [ ] Reformat resource/semantic_conventions/cloud.md
- [ ] Reformat versioning-and-stability.md
- [ ] Reformat baggage/api.md
- [ ] Reformat performance.md
- [ ] Reformat library-guidelines.md
- [ ] Reformat metrics/supplementary-guidelines.md
- [ ] Reformat metrics/sdk.md
- [ ] Reformat metrics/api.md
- [ ] Reformat metrics/README.md
- [ ] Reformat metrics/datamodel.md
- [ ] Reformat metrics/sdk_exporters/in-memory.md
- [ ] Reformat metrics/sdk_exporters/prometheus.md
- [ ] Reformat metrics/sdk_exporters/stdout.md
- [ ] Reformat metrics/sdk_exporters/otlp.md
- [ ] Reformat metrics/semantic_conventions/runtime-environment-metrics.md
- [ ] Reformat metrics/semantic_conventions/system-metrics.md
- [ ] Reformat metrics/semantic_conventions/rpc.md
- [ ] Reformat metrics/semantic_conventions/openmetrics-guidelines.md
- [ ] Reformat metrics/semantic_conventions/faas-metrics.md
- [ ] Reformat metrics/semantic_conventions/README.md
- [ ] Reformat metrics/semantic_conventions/http-metrics.md
- [ ] Reformat metrics/semantic_conventions/process-metrics.md
- [ ] Reformat library-layout.md
- [ ] Reformat trace/sdk.md
- [ ] Reformat trace/api.md
- [ ] Reformat trace/sdk_exporters/zipkin.md
- [ ] Reformat trace/sdk_exporters/jaeger.md
- [ ] Reformat trace/sdk_exporters/non-otlp.md
- [ ] Reformat trace/semantic_conventions/instrumentation/aws-sdk.md
- [ ] Reformat trace/semantic_conventions/instrumentation/aws-lambda.md
- [ ] Reformat trace/semantic_conventions/http.md
- [ ] Reformat trace/semantic_conventions/database.md
- [ ] Reformat trace/semantic_conventions/rpc.md
- [ ] Reformat trace/semantic_conventions/exceptions.md
- [ ] Reformat trace/semantic_conventions/messaging.md
- [ ] Reformat trace/semantic_conventions/README.md
- [ ] Reformat trace/semantic_conventions/faas.md
- [ ] Reformat trace/semantic_conventions/span-general.md
- [ ] Reformat error-handling.md

### PR DESCRIPTION
**Pull request by ocelotl**
Fixes #1210 

There is a framework for specifications from the W3C, the [W3C QA Framework](https://www.w3.org/TR/qaframe-spec/), this is its abstract:

> The goal of this document is to help W3C editors write better specifications, by making a specification easier to interpret without ambiguity and clearer as to what is required in order to conform. It focuses on how to define and specify conformance. It also addresses how a specification might allow variation among conforming implementations. The document presents guidelines or requirements, supplemented with good practices, examples and techniques.

#### What does this PR do?

1. It changes one of the spec documents (`specification/baggage/api.md`) to make it follow the W3C QA framework. This change is intended to show how a document would look after being changed to follow the W3C QA Framework.
2. It adds a script that can parse the spec documents that follow the W3C QA Framework and produce JSON files that can list the included requirements, how mandatory they are and their identifier.
3. Adds a [conformance clause](https://www.w3.org/QA/WG/2004/08/SpecGL-template-text.html) for OpenTelemetry that details how the documents that form this specification are to be written.

#### Why did I create this PR?

While I was working on implementing Metrics, I found myself first having to read all the related documents to find the requirements so that I could know what to implement. This is something that should be as easy as looking for all instances of `MUST`, `SHOULD`, `MAY`, etc but it is not so because there is no guarantee that as the specification is written today every requirement is written in this way (please see [this](https://github.com/open-telemetry/opentelemetry-specification/pull/2003#issuecomment-940984533) comment for examples). I found it necessary then to make this PR more strict in the way it is being written so that its requirements could be extracted from it.

#### What is the general strategy here?

With the approach suggested here we should be able to generate JSON files that contain all requirements so that they can be then transformed into test cases in each implementation. Once an implementation implements and passes all of the mandatory test cases (the ones whose corresponding RFC 2119 keyword is `MUST [NOT]` or equivalent) and it can consider itself compliant.

This idea will require of course rewriting all the documents, but this can be done little by little with one PR per document until we can have all the specification in this format. It is not necessary for this project to stop being developed to format all documents, it continue with some documents in this format and some not.

#### What about the compliance matrix?

The [compliance matrix](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) gathers all the features that each SIG has implemented and marks them as optional or not. I find it convenient but I don't think it is something that gives the level of detail that this approach gives. The compliance matrix is feature-oriented, this approach is requirement-oriented. I think both serve their specific purpose and can continue to exist together.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
It would be useful to to start with the motivation for the change, what are the cons and pros and why we should adopt it.

This appears related to https://github.com/open-telemetry/opentelemetry-specification/pull/1211/files which did not gain traction. What has changed that we should consider this now?

**Comment by jmacd** [comment]
I am a really big fan of this work, @ocelotl!

The OpenTelemetry specification is expansive and written by many authors. As we see from your work on #1956, it is difficult if not impossible to construct a compliance matrix from the text of the specification without having the authors and the community members there to help with interpretation.

It looks like this can be done iteratively: one step at a time, a part of the specification will be rewritten to match the style given here, at which point the compliance matrix row headings can be automatically checked or generated.

Because this is a large PR, I want to encourage you to first (sorry, procedural nits!) file an issue describing the problem "Make the OpenTelemetry specification automatically testable" or something similar. You've already written the motivation above, but we use issues to prioritize discussions about large changes ahead of actual pull requests, usually.

Please file an issue that repeats the motivation and also gives a brief explanation of the steps, e.g., (1) merge the spec-writing guidelines, (2) update document status states to manage the transition, (3) merge the tools for generating x/y/z (4) finally for each component of the specification, (a) refactor, (b) regenerate compliance matrix, (c) ...

**Comment by hdost** [comment]
Is this something that's still being worked on, but maybe elsewhere?

**Comment by ocelotl** [comment]
> Is this something that's still being worked on, but maybe elsewhere?

Not that I am aware of, curious why you ask :sweat_smile:

**Pull request closed without merging**
