### PR TITLE
Fix typo and be specific about literal string

### PR DESCRIPTION
**Pull request by reyang**

### CODE REVIEW

**Comment by reyang** [comment]
@victoraugustolls please help to see if there is anything needs further clarification.

This doesn't cover the URL fix, which was already prepared by @danielkhan in #202.

**Comment by victoraugustolls** [comment]
> @victoraugustolls please help to see if there is anything needs further clarification.

On line `112`, grpc component can be put inside `" "` to follow the changes!

**Comment by reyang** [comment]
> On line `112`, grpc component can be put inside `" "` to follow the changes!

Fixed. Thanks!

**Comment by carlosalberto** [comment]
@reyang Please rebase prior to merging ;)

**Pull request merged**
