### PR TITLE
[editorial] Normalize links in semconv/http-metrics

### PR DESCRIPTION
**Pull request by chalin**
- Clean up in prep for next release of spec
- In scope of https://github.com/open-telemetry/opentelemetry.io/issues/2429
- Related: #2642

### CODE REVIEW

**Review by MrAlias — COMMENTED** [review]
Doesn't the notice at the top of this document prevent changes to this file?

**Comment by chalin** [comment]
It would be nice to be able to fix build warnings before freezing the file. Besides, this is an editorial change. But it your (spec approvers) call.

/cc @svrnm @cartermp

**Review by carlosalberto — APPROVED** [review]

**Comment by reyang** [comment]
@jsuereth I'll leave it to you to decide whether to merge it here or not (if we merge it, we'll need to port the change to the semantic-conventions repo).

**Comment by chalin** [comment]
> Blocking this PR.

Ok, no problem. Shall we just close this PR?

> It's a nice to have, but these files will be slowly "tore down" and pointed to the new semconv repository.

Ok, got it. 

> ... We're not releasing semantic conventions are part of 1.21, that release has moved to the new repository.

If I understand correctly, the semconv pages will be / have been pulled out of the spec? If so, could you open an issue similar to the following:

- https://github.com/open-telemetry/opentelemetry.io/issues/2642

... but for the semconv, so that I can prepare for the page removal on the website side -- and so that we can have a place to discuss whether we still want the semconv pages to be publish on the website in how. If you rather, I can create the issue once you confirm the page move, just let me know.

**Pull request closed without merging**
