### PR TITLE
Prometheus: Allow changing metric names by default when translating from Prometheus to OpenTelemetry

### PR DESCRIPTION
**Pull request by dashpole**
## Changes

The current Prometheus -> OTel spec was written based on the needs of the Prometheus receiver.   Prometheus/client_java recently [released](https://github.com/prometheus/client_java/releases/tag/v1.0.0-alpha-3) OTLP support by following the Prometheus -> OTel spec in the java prometheus client.

When the collector tried to trim suffixes by default in the Prometheus receiver (https://github.com/open-telemetry/opentelemetry-collector-contrib/issues/21743), it broke a number of users, which is why the current language requires not changing metric names.  However, in cases where OTLP export is "new", such as the java prometheus client, it may be acceptable to remove suffixes by default.

This changes the requirement to not alter metric names by default from a MUST to a SHOULD to make it a recommendation.

### CODE REVIEW

**Comment by dashpole** [comment]
@open-telemetry/wg-prometheus @fstab

**Comment by fstab** [comment]
Thanks a lot @dashpole.

**Review by jsuereth — APPROVED** [review]

**Comment by pirgeo** [comment]
Would this also open the path for allowing a refactoring of metric names (e.g. implementing a `NameTranslator` or similar) that would replace underscores with dots or whatever else the user might want? Thinking about semantic conventions for example: if they are already collected in a "compatible" format in the Prom client, could they be exported directly in the dot-notation when exporting to an OTLP consumer? This is probably the wrong issue to discuss this, but I wonder if that is something that would be interesting to folks.

**Comment by dashpole** [comment]
@pirgeo I think whatever mechanism we land on for mapping prometheus names/labels to OTel names/labels, it should live outside of the prometheus exporters/receivers themselves.  I could see schemas potentially solving that problem, as they define a mapping from one naming convention to another.

**Review by jack-berg — APPROVED** [review]

**Pull request merged**
