### PR TITLE
Release 1.21.0

### PR DESCRIPTION
**Pull request by carlosalberto**
May Release.

We will _most likely_ leave schema publishing out of this when https://github.com/open-telemetry/oteps/pull/227 is merged (releases for the schema will happen from the new repo). In the meantime, please review the included changes for this release.

### CODE REVIEW

**Comment by carlosalberto** [comment]
@trask I think so, yes. Once the mentioned OTEP is merged (we already have enough approvals), @jsuereth will split the existing semconv into a new repo, so we will be adjusting things around.

**Review by reyang — DISMISSED** [review]
Blocking for now to coordinate the semantic convention changes https://github.com/open-telemetry/oteps/pull/227.

Here is my understanding of the plan based on the TC discussion/meeting:
* [x] 1. 1.21.0 release from the spec repo will not include semantic convention.
* [x] 2. We aim to have https://github.com/open-telemetry/oteps/pull/227 merged next Monday/Tuesday (May. 8th/9th, 2023).
* [x] 3. @jsuereth will create the new repo https://github.com/open-telemetry/semantic-conventions.
* [x] 4. We expect semantic conventions PRs to move to https://github.com/open-telemetry/semantic-conventions; for certain big PRs that we've already spent lots of efforts and received multiple approvals, it is okay to merge them into the current spec repo given we don't plan to release from the spec repo anyways. The semantic convention YAML/Markdown files will be cherry picked and added to the new repo.
* [x] 5. We'll clean up the spec repo, all the semantic conventions YAML file and related tools/CI will be removed, markdown files will be kept but the content will be replaced with a notice and link to the new place (this is for folks who accidentally use a non-permanent link).
    * #3489
* [ ] 6. The release note of 1.21.0 will be sanitized, with a notice that semantic convention has moved to a new place and there won't be new semantic convention release from this repo anymore.

**Comment by carlosalberto** [comment]
Actually the related OTEP is merged. But Tuesday still sounds good as a target day to complete the remaining steps. Thanks for adding the details on the following steps @reyang !

**Comment by reyang** [comment]
@carlosalberto @jsuereth @trask FYI, [these](https://github.com/open-telemetry/opentelemetry-specification/pulls?q=is%3Apr+is%3Aopen+label%3Aarea%3Asemantic-conventions) are the open PRs that should move to https://github.com/open-telemetry/semantic-conventions (to be created this week) repo.

**Comment by tigrannajaryan** [comment]
I think we need to remove (or somehow make sure it is not published) schema file 1.21.0. We are not releasing a new schema with this spec release, right? So, it should not be published.

**Comment by reyang** [comment]
> I think we need to remove (or somehow make sure it is not published) schema file 1.21.0. We are not releasing a new schema with this spec release, right? So, it should not be published.

Yes, this is bullet point 5 in https://github.com/open-telemetry/opentelemetry-specification/pull/3474#pullrequestreview-1415130195.

**Comment by carlosalberto** [comment]
@jsuereth @reyang I have removed the semantic conventions section from the CHANGELOG, just FYI.

**Comment by carlosalberto** [comment]
@open-telemetry/specs-approvers Please review.

**Review by jsuereth — APPROVED** [review]

**Comment by marcalff** [comment]
Bullet point 4 in https://github.com/open-telemetry/opentelemetry-specification/pull/3474#pullrequestreview-1415130195 is about moving PR.

Should the open issues on area:semantic-conventions be moved to the new repo as well ?

**Review by reyang — APPROVED** [review]

**Pull request merged**
