### PR TITLE
Use hex encoding for trace id and span id fields in OTLP JSON encoding

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Resolves: https://github.com/open-telemetry/opentelemetry-specification/issues/786

See discussion and motivation for the change in the issue linked above.

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Is it a simple way to still use the protobuf encoder with this? Asking for a friend :)))

**Comment by tigrannajaryan** [comment]
I only tried with Gogoproto, and it was not trivial, required a custom marshaler and custom data type for the fields. Here is the draft code on my branch: https://github.com/open-telemetry/opentelemetry-collector/compare/master...tigrannajaryan:feature/tigran/hexid

I am not sure if this is doable with official protobuf libraries and how easy it is.

**Comment by bogdandrutu** [comment]
@tigrannajaryan does it worth the effort then?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan does it worth the effort then?

I think it is worth it, see some thoughts on why here https://github.com/open-telemetry/opentelemetry-specification/issues/786#issuecomment-675053640

Some of the work that is needed to make this work with Gogoproto we wanted to do anyway so that we can reduce the number of allocations for traceid/spanid slices in the Collector by using custom data types. Once it is done there is only some additional work needed to customize the JSON representation.

For some language SDKs this is trivial if I understand correctly (e.g. for JS) since they don't use protobuf JSON encoding capabilities but encode manually instead and it is a one-line change for them.

Even without Protobuf libraries it is not a big stretch to just code the entire JSON marshaling/unmarshaling manually using whatever JSON lib is available. Tests will probably take most of the time if one wants to do this.

**Comment by SergeyKanzhelev** [comment]
It would be super nice to have identifiers as hex. It will simplify life for humans.

**Review by anuraaga — APPROVED** [review]

**Comment by codeboten** [comment]
@tigrannajaryan am I reading this change correctly, 6000+ files changed with 1.9 million lines of code?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan am I reading this change linked in the comments above correctly, 6000+ files changed with 1.9 million lines of code?

Ignore the `vendor` directory. Vendoring the dependencies was just the quickest way to try it.

**Pull request merged**
