### PR TITLE
Minor fixes of typos in trace/{sdk,api}.md

### PR DESCRIPTION
**Pull request by yuanyuanzhao3**
## Changes
Fixes a few typos in the specifications.

### CODE REVIEW

**Comment by reyang** [comment]
Thanks @yuanyuanzhao3! Would you clear the CLA https://github.com/open-telemetry/opentelemetry-specification/pull/4216#issuecomment-2359846072?

**Comment by yuanyuanzhao3** [comment]
> Thanks @yuanyuanzhao3! Would you clear the CLA [#4216 (comment)](https://github.com/open-telemetry/opentelemetry-specification/pull/4216#issuecomment-2359846072)?

done.

**Review by MrAlias — APPROVED** [review]

**Review by dashpole — APPROVED** [review]

**Comment by yuanyuanzhao3** [comment]
can someone approve the workflow run? thanks.

**Review by carlosalberto — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Comment by yuanyuanzhao3** [comment]
I'm also not allowed to merge. I guess I'm too new. Please let me know if there anything I missed. Thanks.

**Comment by cijothomas** [comment]
> I'm also not allowed to merge. I guess I'm too new. Please let me know if there anything I missed. Thanks.

No worries. Only maintainers of this repo can do the merging. Unless there are open conversations/request-for-changes, this is typically merged in couple days. This one is editorial, so likely much faster!
https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#how-to-get-your-pr-merged

**Comment by reyang** [comment]
> > I'm also not allowed to merge. I guess I'm too new. Please let me know if there anything I missed. Thanks.
> 
> No worries. Only maintainers of this repo can do the merging. Unless there are open conversations/request-for-changes, this is typically merged in couple days. This one is editorial, so likely much faster! https://github.com/open-telemetry/opentelemetry-specification/blob/main/CONTRIBUTING.md#how-to-get-your-pr-merged

Faster than your comment @cijothomas 😆

**Comment by cijothomas** [comment]
Concurrent, not parallel 😄

**Comment by yuanyuanzhao3** [comment]
Thanks everyone. That marked my first PR in OTel. Small but it's a start.

**Review by jmacd — COMMENTED** [review]
Thanks @yuanyuanzhao3!

**Pull request merged**
