### PR TITLE
Standardize Notation Conventions

### LINKED ISSUE #298: Notation Conventions
There are many places in this specification where several words are used to signify the requirements in the specification (i.e. "MUST", "MUST NOT", "REQUIRED", "SHOULD", etc.). However, (as far as I can tell) there is no explicit statement of these words significance nor a consistent formatting guideline (none, bold, italicized, capitalized) of them.

Ideally the specification would define the meaning and notational conventions of these words.

For example, including in the [overview](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/overview.md) the following phrase defining these terms according to [RFC 2119](https://tools.ietf.org/html/rfc2119):

> The key words "MUST", "MUST NOT", "REQUIRED", "SHALL", "SHALL NOT", "SHOULD", "SHOULD NOT", "RECOMMENDED",  "MAY", and "OPTIONAL" in this document are to be interpreted as described in [RFC 2119](https://tools.ietf.org/html/rfc2119).

Additionally, it would be ideal if standardized formatting of these words were defined for contributors and a review of the specification was made to ensure consistency in formatting existed.

Looking to other public specifications like [the open container specifications](https://github.com/opencontainers/image-spec/blob/master/spec.md#notational-conventions), it might also make sense to include a phase outlining explicitly the evaluation criteria for an implementation to be compliant with this specification:

> An implementation is not compliant if it fails to satisfy one or more of the MUST, MUST NOT, REQUIRED, SHALL, or SHALL NOT requirements for the protocols it implements. An implementation is compliant if it satisfies all the MUST, MUST NOT, REQUIRED, SHALL, and SHALL NOT requirements for the protocols it implements.

I'm happy to work on this if it is determined to be a valid issue, but want to make sure it is a welcomed change.

### PR DESCRIPTION
**Pull request by MrAlias**
Explicitly specify the meaning and formatting of key words defining the specification requirements according to [bcp14](https://tools.ietf.org/html/bcp14).

Additionally, this makes a best effort attempt to reformat existing specification language to correct the usage of such key words. In most cases this means capitalizing words, but in a few instances there were minor reworking of sentence structure to make this formatting happen.  When the usage of a key word was ambiguous as to whether it was introducing a requirement or merely expository it was interpreted as expository and no modification was made.

Closes #298

### CODE REVIEW

**Comment by Oberon00** [comment]
I don't think you should change all occurrences of SHOULD etc into all-caps just like that. People are likely to just have written SHOULD/MAY/etc based on gut feeling without thinking about it. Which, of course, is bad for a specification, but I think we SHOULD be mindful that we might accidentally put more meaning in a SHOULD/MUST distinction that was intended by the author.

**Comment by MrAlias** [comment]
@Oberon00: I can revert [5f50636](https://github.com/open-telemetry/opentelemetry-specification/pull/308/commits/5f50636c12e07e4353f1cdc6804946bdc644b188) if it is too far reaching.

I agree that imposing meaning after the fact has the potential to be erroneous, but It seems like the ambiguity of these statements needs to be addressed. Without having the clarity on whether statements put into the specification are requirements or merely just supplemental statements leaves open the possibility for different but equally valid interpretations of the specification.

Is this reformatting something that can be tracked in one of the milestones?

**Comment by SergeyKanzhelev** [comment]
@open-telemetry/technical-committee please sign off this.

**Comment by SergeyKanzhelev** [comment]
Active for more than 2 days. Consensus in PR seems to be that we need this declaration and now start fixing up all the specs

**Pull request merged**
