### PR TITLE
[editorial] Ensure all ToCs are generated using markdown-toc

### PR DESCRIPTION
**Pull request by chalin**
Enures that all ToCs are uniformly wrapped in:

- `<!-- toc -->` and `<!-- tocstop -->` so that they get regenerated by `markdown-toc` and checked during CI
- `<details><summary>Table of Contents</summary>` ... `</details>`

/cc @austinlparker

### CODE REVIEW

**Review by arminru — APPROVED** [review]
Thank you!

**Comment by arminru** [comment]
/easycla seems to be stuck, let's see if this helps

**Review by carlosalberto — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by carlosalberto** [comment]
Oops, we should have merged this earlier as it was an editorial change, sorry for that @chalin -- would you mind rebasing and fixing the conflicts?

**Comment by chalin** [comment]
@carlosalberto - rebased, and all checks are green.

**Pull request merged**
