### PR TITLE
[semantic_conventions/resource] fix google platform openshift naming

### LINKED ISSUE #3090: Invalid openshift platform name in semconv 1.16.0
**What are you trying to achieve?**

I would like to identify openshift on in google cloud.

**What did you expect to see?**

A platform attribute with the value `gcp_openshift`.

**Additional context.**

Seems that the attribute wasnt well named in #2985  According to the [documentation](https://github.com/open-telemetry/opentelemetry-specification/blob/791f463964c9a4d5a019408f9b669a30592c7c88/semantic_conventions/resource/cloud.yaml#L141-L144) it should be named `gcp` instead of `google_cloud`.  
> The prefix of the service SHOULD match the one specified in `cloud.provider`.

Like here:

https://github.com/open-telemetry/opentelemetry-specification/blob/791f463964c9a4d5a019408f9b669a30592c7c88/semantic_conventions/resource/cloud.yaml#L119-L128

But it does not.

### PR DESCRIPTION
**Pull request by frzifus**
Fixes #3090

## Changes

Please provide a brief description of the changes here.

Rename google openshift platform attribute.

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Review by joaopgrassi — APPROVED** [review]
Looks good to me. I guess this also needs a changelog entry? Since the values changed 🤔

**Comment by frzifus** [comment]
> Looks good to me. I guess this also needs a changelog entry? Since the values changed thinking

Fair point. Added a changelog entry :+1:

**Review by MrAlias — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Comment by carlosalberto** [comment]
cc @jsuereth

**Comment by frzifus** [comment]
any update here?

**Comment by carlosalberto** [comment]
Maybe @dashpole can confirm?

**Review by dashpole — APPROVED** [review]
Seems reasonable to me, and in-line with other naming.  It isn't a GCP product, obviously, but that also applies to aws_openshift and azure_openshift.

**Pull request merged**
