### PR TITLE
Change OTLP/HTTP port from 4317 to 4318 (#1839)

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Related to https://github.com/open-telemetry/opentelemetry-specification/issues/1816
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/1835
Fixes https://github.com/open-telemetry/opentelemetry-specification/issues/1920

Some historical context: we wanted to make grpc and http use the same port and we
had an open issue in the Collector to do so:
https://github.com/open-telemetry/opentelemetry-collector/issues/1256

The conclusion is that there are technical hurdles that make it unfeasible:
https://github.com/open-telemetry/opentelemetry-collector/issues/1256#issuecomment-880048833

Because of that we need to keep grpc and http ports separate. This means we need to
change the spec to say that otlp/http uses port 4318. Once this PR is merged we
will also need to submit for port 4318 registration with IANA like we did previously
with port 4317:
https://github.com/open-telemetry/opentelemetry-specification/issues/1148#issuecomment-725067404

There was also a draft PR to merge the ports in the Collector but it was not completed:
https://github.com/open-telemetry/opentelemetry-collector/pull/3765

Note that this change was initially submitted in PR https://github.com/open-telemetry/opentelemetry-specification/pull/1839
and then reverted in PR https://github.com/open-telemetry/opentelemetry-specification/pull/1847
because we hoped that the merging could be successfully done. We believe that we should
no longer pursue this and should consider the ports separate from now on.

Note 2: we consider this a spec bug fix (spec was impossible to implement), rather than a 
functionality change, that's why we believe this is an allowed change.

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers please review this PR with a long history of back-and-forth changes. Hopefully this is the last time we touch the port.

**Review by carlosalberto — APPROVED** [review]

**Review by iNikem — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Comment by carlosalberto** [comment]
@open-telemetry/specs-approvers I think we should include this as part of 1.7 to avoid further confusion. Sounds about right?

**Review by bogdandrutu — APPROVED** [review]
Is this a breaking change?

**Review by codeboten — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> Is this a breaking change?

Not for Collector, because Collector already uses separate ports 4317 and 4318 for a while now.

It may be a breaking change for a receiver that expects to receive OTLP/HTTP on port 4317. However I am not aware of any existing implementation that does and given that we met difficulties when trying to have one port on the receiver side it is very likely that no such receivers exist at all.

So, even if it is a breaking change the impact is likely very small and fixing it should be easy (just set an env var on the SDK side to use a different port).

From formal perspective, yes, it is a breaking change because the spec says OTLP/HTTP port is 4318 and it is a Stable section: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#otlphttp
Formally we are not allowed to change any Stable section, but I feel that the real world impact is close to zero. 

However, since we are _unable_ to implement in the Collector what the spec says I think we can treat this as a spec bug, something that is simply wrong and needs to be fixed in the spec. This makes it an allowed change, we are supposed to fix spec bugs even if they mean someone who relied on the bug may be broken as a result of the change.

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers I will keep this open for one more day at least. If there are any doubts please speak up otherwise I will merge and after that will be strongly opposed to reversing/reverting this decision again.

**Comment by anuraaga** [comment]
FWIW, `443` will be a highly common port anyways for non-collector use cases. So indeed the risk of the breaking change seems extremely low.

**Review by jmacd — APPROVED** [review]

**Comment by carlosalberto** [comment]
@tigrannajaryan Are we really to roll? Or you want to wait a little longer?

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan Are we really to roll? Or you want to wait a little longer?

2 more hours to complete 24 hours since I promised at least one more day :-)

**Comment by tigrannajaryan** [comment]
6 approvals, 2 days since last changed, I believe this can be merged.

**Comment by tigrannajaryan** [comment]
@mtwo please file port 4318 with IANA (I believe you know how it's done since you did it last time).

**Comment by mtwo** [comment]
I’ve forgotten, but I’ll read the docs and will file again :)

**Comment by mtwo** [comment]
Filed

**Comment by mtwo** [comment]
Update: my request to extend our existing reservation to the adjacent port was declined, as new port reservations require a new submission. I've since filed submission 1213852 with the IANA and I will reply here when I hear back.

**Comment by prashant-shahi** [comment]
@tigrannajaryan any update on the IANA submission would be very appreciated.

**Comment by tigrannajaryan** [comment]
IANA rejected the request since they don't believe the justification we provided warrants another port registration. The new port will remain unregistered for now until we find stronger arguments to ask for the new port.

**Comment by anuraaga** [comment]
FWIW I completely agree with IANA's decision. HTTP is HTTP regardless of whether the application decides to send gRPC frames or not.

**Comment by tigrannajaryan** [comment]
> FWIW I completely agree with IANA's decision. HTTP is HTTP regardless of whether the application decides to send gRPC frames or not.

@anuraaga Can you help make it happen in the Collector's OTLP receiver? We tried and were unable.

**Comment by anuraaga** [comment]
Maybe, but I am wondering why as the creators of both gRPC and OpenTelemetry (via OC), Google isn't stepping up to take responsibility and fix the mess.

**Pull request merged**
