### PR TITLE
Update api-metrics.md

### PR DESCRIPTION
**Pull request by MrAlias**
Update `Observer` definition to express their monotonic definition the same way as introduced in #312 .

### CODE REVIEW

**Comment by MrAlias** [comment]
@Oberon00: This PR is not an attempt to introduce this wording. Rather, it is one to make the wording consistent with choices that have already been accepted by the specification.

If you are suggesting an alternative working that would comprehensively change not only this but the wording introduced in #312, I feel like that would be better addressed outside of this PR. Possibly as a topic in Gitter, an agenda item at the weekly call, or possibly even a GitHub issue.

**Comment by jmacd** [comment]
Some additional context. Originally we had used different words like "Monotonic" and "NonMonotonic". When it came to Measure metrics, we couldn't find a good opposite for "Absolute". Moreover, having both Monotonic and NonMonotonic options felt confusing, so now we have only two optionals, both which can be true or false.  Counters default to Monotonic = true. Gauges default to Monotonic = false. Measures default to Absolute = true. There are no "opposite" words in use now, which makes the spec more consistent.

**Comment by Oberon00** [comment]
OK, my "request changes" as a non-approver doesn't hold up the PR anyway but if we don't want to have NonMonotonic, what about simply "not monotonic" and "not absolute"?

**Comment by SergeyKanzhelev** [comment]
@Oberon00 I hear your concern. It seems insignificant though. Would it be better to have both there - english word AND `monotonic=false`?

I'm merging it as it's not significant. But feel free to send another PR with the improved wording

**Pull request merged**
