### PR TITLE
Declare OTLP/JSON Stable

### PR DESCRIPTION
**Pull request by tigrannajaryan**
See also https://github.com/open-telemetry/opentelemetry-proto/pull/436

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
We need a lot of eyes on this before we merge this.

**Review by reyang — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]

**Review by Aneurysm9 — APPROVED** [review]

**Review by jsuereth — APPROVED** [review]

**Review by bogdandrutu — COMMENTED** [review]
Would like to clarify the behavior for invalid (all 0) trace/span IDs. In other words we have 3 cases for trace/logs/metrics exemplar:
* "traceId" key is not present
* "traceId" key is present and has an empty value
* "traceId" key is present and value is all 0s

Can we consider these 3 cases the same? Is there a difference between them, if yes, what is the semantic?

**Review by jmacd — APPROVED** [review]

**Comment by jmacd** [comment]
I asked @bogdandrutu because I didn't understand immediately how https://github.com/open-telemetry/opentelemetry-specification/pull/2930#pullrequestreview-1177620347 was supposed to block stabilizing OTLP/JSON.

There are more cases than the three listed above. We expect that TraceIDs should be exactly 32 hex digits and SpanIDs should be exactly 16 hex digits. This follows from the conditions for a "valid" TraceID and SpanID here: https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/api.md#spancontext

We already have language about rejecting invalid data, which makes me think no more specification is needed. We should reject IDs with all zeros, whether it is because they are empty or missing, because valid identifiers require at least one non-zero byte.

**Comment by tigrannajaryan** [comment]
> We already have language about rejecting invalid data, which makes me think no more specification is needed. We should reject IDs with all zeros, whether it is because they are empty or missing, because valid identifiers require at least one non-zero byte.

This is true for Spans but not for LogRecords, where traceid/spanid are optional fields.

**Comment by jmacd** [comment]
> This is true for Spans but not for LogRecords, where traceid/spanid are optional fields.

Bogdan's remark was clear about presence and absence, though https://github.com/open-telemetry/opentelemetry-specification/pull/2930#pullrequestreview-1177620347.

If the "traceId" is absent, then the field is absent, and if the "traceId" is present then the field is present. We only expect valid data when a field is present.

**Comment by bogdandrutu** [comment]
> If the "traceId" is absent, then the field is absent, and if the "traceId" is present then the field is present. We only expect valid data when a field is present.

Does that mean absent is equivalent with present and invalid?

**Comment by Aneurysm9** [comment]
> Does that mean absent is equivalent with present and invalid?

If the field is required, then I would say yes.  If the field is not require, then no.

**Review by codeboten — APPROVED** [review]

**Comment by carlosalberto** [comment]
Hey @tigrannajaryan 

Adding a small note after (briefly) discussing this: the question regarding `trace_id` being missing/empty/all-zeroes is specially important as we are [deviating](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md#json-protobuf-encoding) from the standard protbuf/JSON handling for `trace_id`, hence having this super clear would be important for components such as the Collector.

As discussed: we should at least mention some of the mentioned cases (missing/empty `trace_id`) is undefined behavior.

cc @bogdandrutu @jmacd

**Comment by abitrolly** [comment]
> We need a lot of eyes on this before we merge this.

I can not read the spec. I need to read examples, but there are no examples as long as https://github.com/open-telemetry/opentelemetry-specification/issues/2798 is open.

**Comment by abitrolly** [comment]
Another concern is that spec doesn't cover how to deal with incomplete and missing spans, which should occur quite often in case of errors and exceptions. Basically in cases where the proper trace would be most useful.

https://github.com/open-telemetry/opentelemetry-specification/issues/2773#issuecomment-1245686563

**Comment by tigrannajaryan** [comment]
Depends on https://github.com/open-telemetry/opentelemetry-specification/issues/3040

**Comment by tigrannajaryan** [comment]
> Would like to clarify the behavior for invalid (all 0) trace/span IDs. In other words we have 3 cases for trace/logs/metrics exemplar:
> 
> * "traceId" key is not present
> * "traceId" key is present and has an empty value
> * "traceId" key is present and value is all 0s
> 
> Can we consider these 3 cases the same? Is there a difference between them, if yes, what is the semantic?

Here is a PR to clarify this: https://github.com/open-telemetry/opentelemetry-proto/pull/442

**Comment by tigrannajaryan** [comment]
Not stale. Blocked by https://github.com/open-telemetry/opentelemetry-proto/pull/442

**Review by jonatan-ivanov — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by djaglowski — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Comment by carlosalberto** [comment]
@tigrannajaryan the last blocking issue has been resolved - I think it's time to merge it (and release it as part of the February release).

**Comment by abitrolly** [comment]
IWithout making end of span optional you will have to break the stable implementation, or people will resort to hacks for debugging spans in real-time.

**Comment by carlosalberto** [comment]
@abitrolly Probably a comment for a different PR/issue? Please follow up otherwise with a new issue ;)

**Comment by carlosalberto** [comment]
Merging as 1.18.0  was released.

**Comment by jonatan-ivanov** [comment]
Is there any roadblock in front of marking the whole [OTLP spec](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/protocol/otlp.md) stable (right now it is mixed but its components are stable)?

**Pull request merged**
