### PR TITLE
sdk-tracer: replace Factory with Provider

### PR DESCRIPTION
**Pull request by tsloughter**

### CODE REVIEW

**Comment by tsloughter** [comment]
Trying out doing smaller pieces at a time than the api tracing PR #354

**Comment by carlosalberto** [comment]
Quite needed change, thanks. I'm wondering if we should be strict with regards to this new name (compared to using `Registry` and similar identifiers). I'd say **yes** but I'm wondering if there are languages where `Provider` somehow happens to be a bad identifier (hopefully not).

**Comment by tsloughter** [comment]
It has been discussed in the spec SIG and language agnostic working group. Provider has been the consensus so far.

**Comment by yurishkuro** [comment]
Everyone's approval is useful and has weight, some are B(inding), others NB.

**Pull request merged**
