### PR TITLE
Adding known values for OTEL_PROPAGATORS

### PR DESCRIPTION
**Pull request by codeboten**
## Changes

Adds known propagator values to the environment variables specification.

### CODE REVIEW

**Review by carlosalberto — APPROVED** [review]

**Comment by carlosalberto** [comment]
Overall LGTM - however, I think we need to add a value to specify B3's formats (single and multiple). As the single part is the default, probably we should have something like:

- `b3` specifies single header format.
- `b3multi` (or similar) specifies multiple format.

**Comment by carlosalberto** [comment]
@open-telemetry/specs-approvers Please review this PR.

**Comment by arminru** [comment]
@carlosalberto Should we wait for #961 to settle then or go with just `b3` for now?

**Comment by carlosalberto** [comment]
@arminru As there seems to be initial agreement on having a single B3 Propagator, I'd suggest we go with `b3` for now (if that changes, we can always add a `b3single` or `b3multi` very fast afterwards).

**Review by arminru — APPROVED** [review]

**Pull request merged**
