### PR TITLE
Refine SDK MeterProvider configuration section

### PR DESCRIPTION
**Pull request by pellared**
Towards https://github.com/open-telemetry/opentelemetry-go/issues/3642#issuecomment-1568336829

## Changes

- Create a `MeterProvider - Configuration` section.
- Change "managed solely" to "owned". E.g. I do not think it is wrong that one would pass the same reader to a different metrics provider. But the provider has the permission to e.g. shutdown the reader during metrics provider shutdown.
- Remove _"The SDK MUST provide a way to configure all options that are implemented by the SDK."_ as I do not see any value in this sentence. For me (maybe wrongly) it means like "the configuration MUST by applied".

### CODE REVIEW

**Comment by reyang** [comment]
The tracing spec has something like this https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation. We should consider consistency (might be better to change both).

**Comment by pellared** [comment]
> The tracing spec has something like this https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/trace/sdk.md#tracer-creation. We should consider consistency (might be better to change both).

I created an issue and assigned to myself. I want to make this PR easier (baby steps).

**Review by MrAlias — APPROVED** [review]

**Review by jack-berg — APPROVED** [review]
Saw you created an issue for applying this change to tracing. Can you also create an issue to track making this same change to the [log SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md)?

**Comment by pellared** [comment]
> Saw you created an issue for applying this change to tracing. Can you also create an issue to track making this same change to the [log SDK](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/sdk.md)?

Issue created https://github.com/open-telemetry/opentelemetry-specification/issues/3527

**Review by arminru — APPROVED** [review]

**Comment by pellared** [comment]
Please consider merging the PR 😉

**Comment by jack-berg** [comment]
@pellared can you add a changelog entry?

**Comment by pellared** [comment]
> @pellared can you add a changelog entry?

What do you want me to write there?

```
- Refine SDK MeterProvider configuration section. (#3522)
```

?

**Pull request merged**
