### PR TITLE
Revert #2617, #2675, #2688: "add metrics to replace metrics with `direction`" 

### PR DESCRIPTION
**Pull request by tigrannajaryan**
Please review this carefully. It is not an automatic reverting, I had to fix merge conflicts manually and may have made mistakes, so a thorough review is needed.

Changes:
- This reverts https://github.com/open-telemetry/opentelemetry-specification/pull/2617. We are reverting it until we are certain how to resolve issue #2726
- Also reverts the corresponding schema file changes done in https://github.com/open-telemetry/opentelemetry-specification/pull/2688
- Also reverts https://github.com/open-telemetry/opentelemetry-specification/pull/2675

~Note that this does not revert https://github.com/open-telemetry/opentelemetry-specification/pull/2675 which I believe to still be valid. If you think otherwise please speak.~ [UPDATE: discussed in Spec SIG and decided to revert 2675 too].

Contributes to https://github.com/open-telemetry/opentelemetry-specification/issues/2726

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Please review this carefully. It is not an automatic reverting, I had to fix merge conflicts manually and may have made mistakes, so a thorough review is needed.

**Review by reyang — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers this blocks the release. Please review.

**Comment by tigrannajaryan** [comment]
Note that this does not revert https://github.com/open-telemetry/opentelemetry-specification/pull/2675 which I believe to still be valid. If you think otherwise please speak.

**Comment by Petrie** [comment]
> Note that this does not revert #2675 which I believe to still be valid. If you think otherwise please speak.

@tigrannajaryan  But looks like you already revert it . see [here](https://github.com/open-telemetry/opentelemetry-specification/pull/2748/files#diff-48ed2e166c485f6f64a1a78251b07248e74e9c2a41cfe24e2950b07a5db196b2R131),

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-metrics-approvers please review.

**Review by jsuereth — APPROVED** [review]

**Comment by carlosalberto** [comment]
@tigrannajaryan I'm slightly inclined to revert all the split changes, in order to start 'fresh' and come up with the actual guideline for these cases _and then_ make the change.

**Review by carlosalberto — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Comment by jmacd** [comment]
I support reverting https://github.com/open-telemetry/opentelemetry-specification/pull/2675

**Comment by tigrannajaryan** [comment]
@open-telemetry/specs-approvers I tried to revert carefully, but tables in markdown are tricky. Please review carefully to make sure I did not make mistakes.

**Review by bogdandrutu — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by carlosalberto** [comment]
@tigrannajaryan I think we are good to go (enough reviews, enough time for people to disagree, etc). Good to merge?

**Pull request merged**
