### PR TITLE
Drop log API include_trace_context parameter

### LINKED ISSUE #3394: Consider removing include_trace_context from "Get a Logger" API
include_trace_context parameter has been a source of confusion (see for example [here](https://github.com/open-telemetry/opentelemetry-specification/pull/3387/files#r1165490278)).

I suggest to remove it for now. It is supposed to be an optional parameter, so it can be added later as an optional parameter after we understand its behavior and interaction with the rest of context functionality better. We have a precedent of adding optional parameters to Stable APIs in the past, so it is OK to do so after the Bridge API is declared Stable.

### PR DESCRIPTION
**Pull request by jack-berg**
Resolves #3394.

### CODE REVIEW

**Review by tigrannajaryan — APPROVED** [review]

**Review by reyang — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by jack-berg** [comment]
FYI @martinkuba. If this merges it would supersede #3387. WDYT?

**Comment by jack-berg** [comment]
FYI @scheler I believe `include_trace_context` was originally added by you. See my arguments [here](https://github.com/open-telemetry/opentelemetry-specification/issues/3394#issuecomment-1507441374) for its removal. The same accomplished with `include_trace_context=false` is still possible with this change.

**Comment by martinkuba** [comment]
> FYI @scheler I believe `include_trace_context` was originally added by you. See my arguments [here](https://github.com/open-telemetry/opentelemetry-specification/issues/3394#issuecomment-1507441374) for its removal. The same accomplished with `include_trace_context=false` is still possible with this change.

@jack-berg If I am reading this change correctly, the trace context will always be populated (it says MUST). So, if I did not want the trace context populated, I would have to call logger.emit() with empty context parameter. But I think that means that processors would also get empty context? I don't think that's a side effect that we want.

With that said, I don't know if there is a use case for not wanting to set trace context.

**Comment by jack-berg** [comment]
@martinkuba you can achieve the goal of having `LogProcessor#onEmit(Context,LogRecord)` have a useful context while `LogRecord` has empty trace context fields by setting explicit context when calling logger.emit, but first removing the trace context. In java, I'd accomplish this with `Context.current().with(Span.getInvalid())`.

**Comment by martinkuba** [comment]
> @martinkuba you can achieve the goal of having `LogProcessor#onEmit(Context,LogRecord)` have a useful context while `LogRecord` has empty trace context fields by setting explicit context when calling logger.emit, but first removing the trace context. In java, I'd accomplish this with `Context.current().with(Span.getInvalid())`.

I think that's a good workaround but more inconvenient than having a logger instance that does not add the trace context to any logs it emits. I am just pointing out the difference but do not feel strongly about keeping this configuration.

**Comment by scheler** [comment]
@jack-berg  this is fine. When the logs api was introduced it did not list out the parameters for logger operations explicitly. With the section on implicit context injection, I felt the need for a setting to avoid setting context on the log record. 

Now with the explicit Context parameter in logger.emit, is there still a need to have these two sections in the spec?

[Implicit Context Injection](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#implicit-context-injection)

[Explicit Context Injection](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#explicit-context-injection)

**Comment by tigrannajaryan** [comment]
> Now with the explicit Context parameter in logger.emit, is there still a need to have these two sections in the spec?
> 
> [Implicit Context Injection](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#implicit-context-injection)
> 
> [Explicit Context Injection](https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/logs/bridge-api.md#explicit-context-injection)

I think the sections are still necessary to explain how it is supposed to work. This PR makes the necessary changes in those sections.

**Comment by jack-berg** [comment]
> I think that's a good workaround but more inconvenient than having a logger instance that does not add the trace context to any logs it emits.

Luckily its log appenders that call this API so they only need to write the code that excludes trace context context in one place.

> I think the sections are still necessary to explain how it is supposed to work. This PR makes the necessary changes in those sections.

I took another look at those sections and wasn't satisfied with how their language had diverged from language we use elsewhere in the document. I rephrased it for consistency.

**Review by jsuereth — APPROVED** [review]

**Pull request merged**
