### PR TITLE
Rename samplers package to util

### PR DESCRIPTION
**Pull request by pavolloffay**
Sync after change in java https://github.com/open-telemetry/opentelemetry-java/issues/391.

Signed-off-by: Pavol Loffay <ploffay@redhat.com>

### CODE REVIEW

**Comment by yurishkuro** [comment]
why are we making this change? "samplers" is a much better name for sampler classes.

**Comment by SergeyKanzhelev** [comment]
I believe it's language specific for java. From the comments on original issue:

> Following the same mode as Collections, Arrays do in java lang we should probably move the Samplers under an util sub-package under trace.
> 
> Also for Event and Link interfaces the default implementation can be under Events, Links classes that will expose a create static method. Events and Links can also be in util.

So perhaps we can just remove this subfolder altogether to eliminate confusions

**Comment by yurishkuro** [comment]
big -1 on anything called "util". Java stdlib design is not the template to follow (how terrible would it be if they called it `java.collections` instead of `java.util.collections`?)

removing subdir makes sense. I don't see much value in being overly prescriptive at this stage.

**Comment by carlosalberto** [comment]
Besides being language specific, I have to say I have mixed feelings - yes, it's something the Java class library does, but as @yurishkuro said, we don't have to follow this - in that side, in .Net collections exist under `System.Collections`, and everybody is fine with it ;)

**Comment by SergeyKanzhelev** [comment]
@iredelmeier please file an issue if you feel that packaging example is not needed.

**Pull request merged**
