### PR TITLE
Add k8s.node semantic convention

### PR DESCRIPTION
**Pull request by jrcamp**
## Changes

Add `k8s.node` semantic convention to existing k8s conventions.

### CODE REVIEW

**Comment by kenfinnigan** [comment]
I'm curious to learn the benefits of tracking Kubernetes Node in addition to Pods?

Would you expect one or the other to be captured or both?

**Comment by bogdandrutu** [comment]
Duplicate of https://github.com/open-telemetry/opentelemetry-specification/pull/1341 ?

**Comment by jrcamp** [comment]
> Duplicate of #1341 ?

Sorta but this also adds uid and that other one is stale.

**Comment by jrcamp** [comment]
> I'm curious to learn the benefits of tracking Kubernetes Node in addition to Pods?

You may want to filter your metrics or spans by a kubernetes node name.

> Would you expect one or the other to be captured or both?

Would expect both.

**Comment by kenfinnigan** [comment]
Thanks @jrcamp

**Review by tigrannajaryan — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by arminru — APPROVED** [review]

**Comment by jrcamp** [comment]
@bogdandrutu can you merge?

**Review by carlosalberto — APPROVED** [review]

**Review by XSAM — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
@jrcamp please resolve the conflict.

**Pull request merged**
