### PR TITLE
Revert "Rename SpanContext to SpanReference. (#1075)"

### LINKED ISSUE #1126: Rename SpanReference to SpanContext (revert #1075)
**What are you trying to achieve?**

Revert #1075 after it was badly received in the actual implementations. Overall, the reasons behind going back to `SpanContext` are:

* `SpanContext` is an already *very* well known term.
* `SpanReference` may make people think of pointers/references.
* `SpanReference` includes additional information to `Span`s, such as `tracestate`.
* Too late in the game to make this change overall, as well as the lack of a true perfect solution.

For this change, we will actually expect more than the usual reviews, in order to verify with SIG maintainers/approvers this is a good thing.

### PR DESCRIPTION
**Pull request by carlosalberto**
Fixes #1126 

I'd like to get the eyes of as many people as possible. We will also reserve a few days before (hopefully) merging this.

### CODE REVIEW

**Review by jmacd — APPROVED** [review]
This was discussed extensively in yesterday's Spec SIG (APAC) call. We found among the group general consensus that SpanContext is not a perfect term, but that the cost of changing from SpanContext (which is well established) is too high to justify the change.

**Review by tigrannajaryan — APPROVED** [review]
I don't have a strong opinion, approving to indicate I saw this and fine with the change.
I advise all @open-telemetry/specs-approvers and language maintainers to also indicate that they saw this even if you don't have any comments.

**Review by obecny — APPROVED** [review]
lgtm

**Comment by dyladan** [comment]
Seems fine to me. I think we've used the term "context" in far too many places. The cost of changing now is high, but what is the point of alpha/beta cycles if not to make expensive changes before GA?

**Review by tsloughter — APPROVED** [review]

**Comment by tsloughter** [comment]
Put my reasoning for approval in the issue https://github.com/open-telemetry/opentelemetry-specification/issues/1126#issuecomment-713868591

**Review by codeboten — APPROVED** [review]

**Review by anuraaga — APPROVED** [review]
I still slightly favor `SpanReference`, but probably because it's more idiomatic in Java than other languages since everything's a reference anyways. For the record, this is the sort of code that's unfortunately bemuddled with two contexts, but I understand the motivation to not make a big change at this point

`Span.fromContext(context).getSpanContext()`

**Review by iNikem — APPROVED** [review]

**Review by Oberon00 — APPROVED** [review]
Approving because I agree the cost of renaming may be too high. I do think that SpanReference is the better name for that concept though.

**Review by arminru — APPROVED** [review]
Same as @Oberon00.
@carlosalberto you might want to indicate in the changelog that the change was reverted.

**Review by reyang — APPROVED** [review]

**Comment by carlosalberto** [comment]
@arminru Removed the original entry in the CHANGELOG regarding the rename to `SpanReference` ;) Hope that works!

**Comment by bogdandrutu** [comment]
Wow only 10 approvals :))

**Review by bogdandrutu — APPROVED** [review]

**Comment by carlosalberto** [comment]
Merging this as we have 1) enough approvals (7 approvers and 3 language SIG approvers), and 2) let it soak for a pair of days already.

**Pull request merged**
