### PR TITLE
Temporarily remove `tracestate`

### PR DESCRIPTION
**Pull request by iredelmeier**
Per a discussion in the W3C Trace-Context meeting today, it feels safest to (*temporarily!*) remove `tracestate` from OpenTelemetry.

Its use in OpenTelemetry itself is currently ambiguous, e.g., should it be used to propagate tags and, if so, how do we want to encode them? Rushing this decision while there are still open, higher-level questions about distributed context in OpenTelemetry feels like a mistake, as it would likely lead to either a painful breaking change or being stuck with a bad decision. On the other hand, waiting until we've thought through it some more allows us to implement the decision as an *additive* decision.

Removing tracestate propagation could impact some vendors. We believe that this is unlikely, since most of the vendors actually using Trace-Context either were present for the meeting and confirmed they shouldn't be affected or have otherwise mentioned they're not yet using tracestate. **Please speak up if you're aware of a vendor or other party that would be affected!**

### CODE REVIEW

**Comment by tedsuo** [comment]
Just for clarity, is the request just remove TraceState from the API? Or are we also asking SDKs not to propagate it any more. Is TraceState in flux within the W3C proposal?

I agree that there is little obvious utility in exposing `TraceState` in the API, as its contents are by definition an implementation detail. There is a good case to make, which says that if developers are accessing `TraceState` to make decisions in their code, that is effectively the same as casting the tracer API to a specific implementation. 

As with any case where users are feeling forced to do a cast, we would first want to understand the requirements and then expose an API in a vendor-neutral manner.

**Comment by mtwo** [comment]
I think that it's a discussion for (a) removing TraceState from the API and (b) determining if Tags should use TraceState (while still not exposing the TraceState API directly). I don't have a strong opinion, but we should be clear to each language's SIG about how they're expected to handle the TraceContext header.

**Comment by bogdandrutu** [comment]
I think the TraceState is independent of tags (at least based on my understanding). Happy for the moment to remove it, fyi this change is not compatible with OpenCensus, so we may need to double check that.

**Comment by bogdandrutu** [comment]
@yurishkuro that is exactly my understanding as well.

**Comment by iredelmeier** [comment]
@songy23 done!

**Comment by bogdandrutu** [comment]
I am not sure I understand the motivation to remove it (at least the one in the description). Tags/DistributedContext are as @yurishkuro mentioned independent of this so I do not understand why this PR should be merged.

**Comment by bogdandrutu** [comment]
Also this will break OpenCensus so probably we cannot remove it. There is no other way that existing OpenCensus Tracestate can be replaced.

**Comment by yurishkuro** [comment]
as I understand the PR, it's not about removing `tracestate` from w3c-compliant encoders, but from the Spec and API.

**Comment by discostu105** [comment]
If I understand correctly, this is about removing TraceState from the API layer only. In that case I am absolutely for it. I don't think an application developer should read/write TraceState at all. It's a concern of the tracing library only.

Would the default OpenTelemetry implementation (SDK) still implement TraceState propagation?

In case of a custom tracer API implementation (OpenTracing style), the Tracer is free to choose if it wants to implement TraceContext (including TraceState) or not.

**Comment by bogdandrutu** [comment]
@reyang I agree, but that is not what I understand from the description and from the changes. I think we need to be w3c compatible and not propagating the tracestate is against the standard.

I do think that tracestate API can be removed until we learn better how to expose mutators or how do the users will use it, but we cannot drop it if we received. We may be able to drop the serialization/deserialization and validation but we probably still need to propagate what we received.

Happy to be convinced otherwise.

@discostu105 one option to allow users to extend the SpanContext is to not make it final so that a different SDK implementation can choose to extend that class and include the tracestate.

Question for all:
1) When we do want to do log correlation do we want to also include the tracestate in the logs?

**Comment by lizthegrey** [comment]
@bogdandrutu and I discussed today that `tracestate` needs to be used by the SDK to pass the sampling rate between spans... and therefore that while it's fine to remove for September 1, we will need it by October 15 in order to ensure metrics calculated from rate of observed post-sampling spans are correct.

**Comment by tedsuo** [comment]
@lizthegrey I think that's the correct assessment. TraceState is propagated, and available to the SDK, but not readable via the API for now. 

@iredelmeier, does that match your original intention?

**Comment by lizthegrey** [comment]
> @lizthegrey I think that's the correct assessment. TraceState is propagated, and available to the SDK, but not readable via the API for now.
> 
> @iredelmeier, does that match your original intention?

ping @iredelmeier -- this is blocking me from being able to extend https://github.com/open-telemetry/rfcs/pull/24 to include information on sample rates in the `tracestate`  as part of the default SDK `Sampler` implementations and the `Sampler` SDK interface.

**Comment by SergeyKanzhelev** [comment]
The discussion of this issue ended month ago. And the branch is stale and have a lot of conflicts.

@iredelmeier I am closing this PR for now. Please re-open if needed

**Pull request closed without merging**
