### PR TITLE
Add notes about MetricExporter naming

### PR DESCRIPTION
**Pull request by legendecas**
## Changes

If the implementors choose to implement pull metric exporters modeled as a metric reader, the only variant for metric exporter interface is push metric exporter. While the pull metric exporter is modeled as a "metric reader", the better naming for the genric "metric exporter" interface may be "push metric exporter".

Just open this PR to see if there are similar naming confusions with other SDK implementors. If so, I'd believe the metric exporter and metric reader section need a re-structure in a follow-up PR since how the pull metric exporter is modeled is important to the naming of the metric exporter interface.

Related:
- https://github.com/open-telemetry/opentelemetry-js/pull/2707
- https://github.com/open-telemetry/opentelemetry-js/issues/2589#issuecomment-1007723767

### CODE REVIEW

**Review by reyang — APPROVED** [review]
LGTM.

**Review by jsuereth — APPROVED** [review]

**Review by cijothomas — APPROVED** [review]

**Review by carlosalberto — APPROVED** [review]

**Review by jmacd — APPROVED** [review]
Agree that MetricReader/PushMetricExporter are acceptable choices

**Comment by legendecas** [comment]
@bogdandrutu 👋  friendly pinging assignee. we have 6 approvals, would you mind landing this one? thank you!

**Review by Rauno56 — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
Enough approvals, more than 2 days since last comment/change. Merging.

**Pull request merged**
