### PR TITLE
Add thread semantic attributes for logs

### PR DESCRIPTION
**Pull request by trask**
## Changes

Adds thread semantic attributes for logs, copied from the thread semantic attributes for spans.

### CODE REVIEW

**Review by arminru — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
> Adds thread semantic attributes for logs, copied from the thread semantic attributes for spans.

I don't think copying is the right approach. This creates unnecessary maintenance burden. A significant potion of attributes that can be recorded on spans can also be recorded on logs. Copying is not going to work.

We discussed this in the past and the thinking is that we need to move semantic convention to a common directory. @tedsuo had a PR which did not move forward: https://github.com/open-telemetry/opentelemetry-specification/pull/1977/files

Perhaps it is time to revive it.

**Review by bogdandrutu — COMMENTED** [review]
Why do we not use the tool to generate these attributes from yaml?

**Comment by trask** [comment]
Closing for now as there's a lot of prerequisite tooling work and spec restructuring before this PR can move forward.

**Comment by bogdandrutu** [comment]
@tigrannajaryan @trask would be good to at least start a tracking issue for this.

**Pull request closed without merging**
