### PR TITLE
Declare OTLP stable

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
Since OTLP/JSON was declared stable, all the parts of the OTLP spec is stable so the whole spec should be declared as such
See gh-2930

### CODE REVIEW

**Review by jsuereth — APPROVED** [review]

**Review by reyang — APPROVED** [review]
Maybe we should move the "Stable" tag from individual sections?

**Comment by jsuereth** [comment]
Can you also remove the "status" callouts in subsections since the whole document is marked stable?

**Comment by jonatan-ivanov** [comment]
👍🏼 I also removed the signal maturity level section.

**Review by carlosalberto — CHANGES_REQUESTED** [review]
Blocking this changes as, _I think_, there are some last conditions before we can declare OTLP stable as a whole: https://github.com/open-telemetry/opentelemetry-proto/issues/400 

@tigrannajaryan would you mind taking a look? Discard this changes request otherwise.

**Comment by jonatan-ivanov** [comment]
@carlosalberto Might worth putting a line or two in OTLP spec about why it is not stable yet if all of its components are declared as stable.

**Comment by tigrannajaryan** [comment]
This should be fine, I don't see anything that remains experimental.

Let's not rush it though and give us time to think through.

A question: do we have sufficiently clear understanding of what "Stable" means for this document or we need to spell it out explicitly?

**Comment by jonatan-ivanov** [comment]
@tigrannajaryan Can you bring this up in the next spec meeting to see what others think?

**Review by carlosalberto — APPROVED** [review]

**Review by jmacd — APPROVED** [review]

**Pull request merged**
