### PR TITLE
Issues #3132, #3133: Semconv for hardware metrics, network metrics and attributes

### LINKED ISSUE #3132: Definition of 'hw.errors' metric for hardware network adapter and physical disks are ambiguous
**What are you trying to achieve?**

Improve the definition of the `hw.errors` metric in guidelines for **hardware network adapter** and **physical disk** .  Add one or more attribute to qualify the type of errors.

**What did you expect to see?**

The definition of the `hw.errors` metric in hardware network adapter should not be ambiguous. I'm guessing the intent is to count the number of packets that contained errors preventing them from being delivered, i.e., I/O errors, but the spec is not clear. Maybe the intent was to count **any** error that could happen on the **adapter**, including count of packet errors (IO errors), hardware component failures and chipset errors.

**Additional context.**

## General Case

In the general case, the spec defines the `hw.errors` metric as *the number of errors encountered by the component*. Since the type of error is not qualified, this could include any type of error, such as hardware failure, firmware bugs, I/O bus errors, I/O device errors, machine check exceptions, etc. It's a bit odd to use a single metric for all of these types of errors.

## hw.errors in Network adapter metrics

In the [network adapter metrics](https://opentelemetry.io/docs/reference/specification/metrics/semantic_conventions/hardware-metrics/#hwnetwork---network-adapter-metrics), the `hw.errors` is defined as *the number of errors encountered by the network adapter*.

For packet I/O errors, it's useful to know the `direction` of the error. I.e. counting the number of received packets that couldn't be delivered (malformed packet, CRC error, buffer full, etc) versus the number of packets that could not be transmitted.

If the spec is not clear, that could mean different instruments report network and disk `hw.errors` in different ways. Some implementation may only report I/O errors, while other implementations could report hardware errors, which are very different.

For example, if a chipset error occurs, the network adapter may have to be replaced. If packets with wrong CRC are received, the network adapter has most likely nothing to do with the problem. It could be a software issue or a hardware problem on a remote system. The errors could also be injected intentionally to test how systems handle network I/O errors.

## hw.errors in Physical Disk Errors

This is similar to network errors. Physical disks expose many error counters through SMART, including IO errors (e.g. read errors, write errors, and errors that are not about I/O.

## Proposal

1. Add optional `direction` attribute for `hw.errors`. This will help to distinguish between ingress versus egress errors on the network interface. But see #3131.
1. Add one more attribute to identify the type of error, e.g., is it an I/O error or hardware error.

### PR DESCRIPTION
**Pull request by bertysentry**
Fixes #3132, #3133

## Changes

In semantic conventions for hardware metrics:

* Updated network adapter description
* Changed `type` to `hw.error.type` for the `hw.errors` metric

### CODE REVIEW

**Comment by jmacd** [comment]
Question for @open-telemetry/specs-metrics-approvers what is the status of our build tools for generating changes such as this [in the yaml specification](https://github.com/open-telemetry/opentelemetry-specification/tree/main/semantic_conventions/metrics)? I'm having trouble reading these diffs, but the changes look good.

**Review by jmacd — APPROVED** [review]

**Comment by bertysentry** [comment]
@jmacd Yeah that will be my next change in the semantic conventions for hardware metrics!

**Review by trask — APPROVED** [review]

**Review by bogdandrutu — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by carlosalberto** [comment]
@bertysentry Hey, could you update this branch so we can merge? (or even better, allow us to update it, if possible ;) )

**Comment by bertysentry** [comment]
@carlosalberto PR updated! I would like to authorize upstream to update the branch on the fork, but it looks like it's not possible because the forked repo belongs to my organization, and not to me personally. Maybe next time, I'll fork using my personal account, instead of my organization.

**Pull request merged**
