### PR TITLE
Clarify formatter and implementation options for lazy links and events

### LINKED ISSUE #222: Tracer API: What is the API for LinkFormatter / EventFormatter
The tracer API specifies that there should be a method to add a lazy link and that:

> This can be implemented by providing a Link interface or a concrete Link definition and a LinkFormatter

It does not specify the API or behavior of a `LinkFormatter`. If a language wants to provide a concrete `Link` implementation, what should should it provide as a `LinkFormatter`.

This is the same situation for `Event` / `EventFormatter`. 

I searched through the repos for several other languages and found that all of them were providing an interface. Can anyone elaborate on what a solution using a concrete class and a formatter would look like?

### PR DESCRIPTION
**Pull request by mwear**
This PR is a result of #222 and clarifies the role of a `LinkFormatter` or `EventFormatter` as well as potential implementations regarding lazy links and events.

To recap from #222.

> A `LinkFormatter` is a function that returns a `Link`. For languages such as Go, the function can return a concrete object that will be stack-allocated, whereas an interface would be heap-allocated.

For dynamic languages without interfaces, such as Ruby, being able to use a concrete `Link` or `Event` class will be beneficial. That case is spelled out in the edits in this PR.

The final change is that `Link`s and `Event`s do not need to be lazily initialized, rather their properties should be lazily accessed, when formatting attributes, for example.

cc: @bogdandrutu 

Fixes #222

### CODE REVIEW

**Comment by jmacd** [comment]
About lazy events, specifically, I wonder if you would be more-or-less interested in having support for lazy values as opposed to lazy events. 

I ask because, in Go (and probably other languages), we've used a common value type for the value of a span attribute and a log field. If one possible value type was lazily-evaluated, then we'd have support for lazy attributes and lazy log fields. I'd prefer to see lazy values supported, would give up lazy event support if I had it. Here's the related discussion:

https://github.com/open-telemetry/opentelemetry-go/issues/57

**Comment by bogdandrutu** [comment]
@jmacd I think you are referring to what I described in my previous comment as the second option. I think the specs should allow language devs to chose the most language specific solution. These two that I wrote are probably a sub-set of all possible solutions to achieve the same capability,

**Comment by jmacd** [comment]
I agree that how the lazy interface appears should be decided in each language, and wasn't trying to comment about links specifically. I was trying to suggest that for events, specifically, we might avoid requiring a lazy interface entirely (lazy for of AddEvent), since we could instead require lazy values.  I'm suggesting that we may not require both lazy values and lazy events.

**Comment by bogdandrutu** [comment]
Can you please describe to me what a "lazy value" is?

>  I was trying to suggest that for events, specifically, we might avoid requiring a lazy interface entirely (lazy for of AddEvent), since we could instead require lazy values. I'm suggesting that we may not require both lazy values and lazy events.

Can you please clarify what is "value" and what is "event" in the these sentences?

**Comment by jmacd** [comment]
OpenTracing didn't explicitly talk about lazy values, but of its "Log" interface (which equates with OTel Events), it writes:
```
Required parameters

One or more key:value pairs, where the keys must be strings and the values may have any type at all. Some OpenTracing implementations may handle more (or more of) certain log values than others.
```

Because of the desire to not compute things that won't be recorded because of sampling, there was a demand to support logs with lazily-evaluated values. These are logged values that avoid some cost if the span is not recorded.

OTOH, this PR is about a lazy Event interface, which avoids some cost when a span is not recorded. There are two potential ways to get the cost savings we're after, with a lazy event:

```
  span.AddLazyEvent(some_object_that_emits_an_event)
```

or with a non-lazy event and lazy values, e.g.,

```
  span.AddEvent("message", Field(key, Lazy(some_object_that_emits_a_value))
```

I'm suggesting that the lazy value support makes less work for the programmer. It also makes the possibility of lazy span attributes, e.g., 

```
  span.SetAttribute(key, Lazy(value))
```

**Comment by jmacd** [comment]
This is the OpenTracing-Go Lazy log field support: https://github.com/opentracing/opentracing-go/blob/135aa78c6f95b4a199daf2f0470d231136cbbd0c/log/field.go#L143

**Comment by jmacd** [comment]
I put lazy value support into this prototype for OTel-Go: https://github.com/jmacd/opentelemetry-go/pull/3/files#diff-63798501ace4c677ca3aa1db1d696936R179

**Comment by bogdandrutu** [comment]
If I understand correctly the intention is to support "laziness" only for a subset of the properties for the Event. I do like that you also provide the "laziness" for the attributes as well.

Why do you not want to support lazy for the Key for example or for the "message"?

I think I start to like that if we offer a Lazy formatting version for attributes the same can be used for the Event.attributes.

**Comment by jmacd** [comment]
The idea is that the message should be a constant string, not a variable. It's a prescriptive position, but there are a number of structured logging libraries out there that encourage thinking of a log event as a constant string and a list of key:value variables.

**Comment by bogdandrutu** [comment]
@jmacd I am fine with that, but would like to know if others would think of a Event.message where this is not a literal or a Link.Attributes.Key where that is not a literal.

**Comment by mwear** [comment]
@bogdandrutu

Thanks for the code snippets in your [comment](https://github.com/open-telemetry/opentelemetry-specification/pull/228#pullrequestreview-278635705). They are helpful in trying to clarify what is expected. I recognized the lack laziness in https://github.com/open-telemetry/opentelemetry-ruby/pull/54 and laid out several options to address that. Options 2 and 3 from [this comment](https://github.com/open-telemetry/opentelemetry-ruby/pull/54#issuecomment-523646334) are fairly close to the code you wrote earlier.

So, to clarify for lazy links and lazy events, formatting attributes is the potentially expensive operation, and a lazy link or event, should have a way to defer their initialization. This is so that you can avoid the work if the link or event is not used. If this is correct, I'd propose changing the text to read:

- An API to record a single `Link` whose attributes are lazily constructed in 
order to avoid unnecessary work if a link is unused. If the language supports 
overloads then this SHOULD be called `AddLink` otherwise `AddLazyLink` MAY be 
considered. In some languages, it might be easier to defer `Link` or attribute 
creation entirely by providing a wrapping class or function that returns a 
`Link`. When providing a wrapping class or function that returns a `Link` it
should be named `LinkFormatter`.

Let me know if that clarifies things, and I'll make those changes to the PR. If it can be improved further, let me know.

**Comment by bogdandrutu** [comment]
@mwear only one small caveat here is the fact that we need the same optimization for attributes, links, events in all cases we are focused on attributes. As @jmacd another approach is to allow lazy creation of the attribute value only and presume that all the other fields are cheap to construct.

Your current suggestion matches perfectly with my intention/understanding so the change that @jmacd proposed will be a change to the spec but I kind of like it if we all agree that only the values require lazy formatting.

**Comment by mwear** [comment]
@bogdandrutu and @jmacd: How does this look:

- An API to record a single `Link` whose attributes or attribute values are 
lazily constructed, with the intention of avoiding unnecessary work if a link is 
unused. If the language supports overloads then this SHOULD be called `AddLink`
otherwise `AddLazyLink` MAY be considered. In some languages, it might be easier
to defer `Link` or attribute creation entirely by providing a wrapping class or
function that returns a `Link`. When providing a wrapping class or function that
returns a `Link` it should be named `LinkFormatter`.

Let me know if there are any other suggestions I should incorporate. If this covers everything, I'll update the spec for Links and Events.

**Comment by yurishkuro** [comment]
> if we all agree that only the values require lazy formatting.

Lazy providers for _collection_ of attributes come in handy in API translations.

Has anyone looked at Honeycomb APIs? Structured events are their bread and butter. cc @lizthegrey

**Comment by mwear** [comment]
Is there anything I can do to help move this forward?

**Comment by bogdandrutu** [comment]
Please update and re-base. Will try to merge this after.

**Comment by Oberon00** [comment]
Please clarify when the lazy "formatting" is done: At export time or immediately when calling the AddLazy* method? Or at an unspecified time within these?

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu it seems that you was fine with the latest proposal. Please sign off than or comment furter

**Pull request merged**
