### PR TITLE
Update semconv for hardware metrics to use `direction` attributes

### LINKED ISSUE #2805: Semantic conventions for hardware metrics need to be updated to merge network metrics and GPU IOs metrics
Following discussion in #2726, the semantic conventions for hardware metrics (`specification\metrics\semantic_conventions\hardware-metrics.md`) must be updated to merge IO metrics using the `direction` attribute:

| Current metris | Merged metric |
|---|---|
| `hw.gpu.io.receive`, `hw.gpu.io.transmit` | `hw.gpu.io` with `direction` set to `receive` or `transmit` |
| `hw.network.io.receive`, `hw.network.io.transmit` | `hw.network.io` with `direction` set to `receive` or `transmit` |
| `hw.network.packets.receive`, `hw.network.packets.transmit` | `hw.network.packets` with `direction` set to `receive` or `transmit` |

### PR DESCRIPTION
**Pull request by bertysentry**
Fixes #2805

## Changes

Updated semantic conventions for hardware metrics (`specification\metrics\semantic_conventions\hardware-metrics.md`) to use the `direction` attributes (and follow updated general semantic conventions).

* `hw.gpu.io.receive`, `hw.gpu.io.transmit` ==> `hw.gpu.io`
* `hw.network.io.receive`, `hw.network.io.transmit` ==> `hw.network.io`
* `hw.network.packets.receive`, `hw.network.packets.transmit` ==> `hw.network.packets`

### CODE REVIEW

**Review by jmacd — APPROVED** [review]

**Comment by bertysentry** [comment]
Thank you @jmacd! 
@arminru, please review and approve 😊

**Review by jack-berg — APPROVED** [review]
Please add a changelog entry!

**Comment by bertysentry** [comment]
@jack-berg CHANGELOG entry added!

**Comment by carlosalberto** [comment]
This seems like a straightforward change to comply with the other metrics we already have

cc @jsuereth

**Review by arminru — APPROVED** [review]

**Comment by bertysentry** [comment]
Since everybody approved this, I guess it's time to hit that green Merge button 😉

**Comment by carlosalberto** [comment]
@bertysentry Agreed. Sorry, can you merge again? :(

**Comment by bertysentry** [comment]
@carlosalberto Merge done, all checks have passed, we're good to go! Thank you!

**Pull request merged**
