### PR TITLE
Fixes missing Copyright holder

### PR DESCRIPTION
**Pull request by danielkhan**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
I think we don't need to modify the LICENSE file

**Comment by SergeyKanzhelev** [comment]
@bogdandrutu I don't think it hurts to have it fixed. Definitely looks better without the placeholder

**Comment by bogdandrutu** [comment]
Do you know if other projects do the same? Or this should be a standard format?

**Comment by danielkhan** [comment]
It's a placeholder that is often overseen. I don't know the legal implications but the intent of the placeholder was clearly to be replaced :)

**Comment by SergeyKanzhelev** [comment]
@danielkhan please re-open if you feel it needs to be changed.

**Comment by danielkhan** [comment]
I think you are right, @SergeyKanzhelev. While there are projects that filled it out, like https://github.com/istio/istio/blob/master/LICENSE#L190, the majority hasn't.

**Pull request closed without merging**
