### PR TITLE
add optional otel_scope_info configuration for prometheus exporter

### PR DESCRIPTION
**Pull request by codeboten**
## Changes

Adding some more options that are exposed in the OTel Go SDK, but not specified in the prometheus exporter details.

* [x] Related issues https://github.com/open-telemetry/opentelemetry-configuration/issues/59
* [x] [`CHANGELOG.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/CHANGELOG.md) file updated for non-trivial changes
* [ ] [`spec-compliance-matrix.md`](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md) updated if necessary

### CODE REVIEW

**Review by jack-berg — APPROVED** [review]
Programmatic support for this is being added to opentelemetry-java in https://github.com/open-telemetry/opentelemetry-java/pull/6015

**Comment by codeboten** [comment]
Note this requirement is captured in the prom compatibility doc https://github.com/open-telemetry/opentelemetry-specification/blob/main/specification/compatibility/prometheus_and_openmetrics.md#instrumentation-scope-1

**Comment by carlosalberto** [comment]
cc @dashpole

**Review by carlosalberto — APPROVED** [review]

**Review by MrAlias — APPROVED** [review]

**Comment by MrAlias** [comment]
cc @dashpole

**Review by reyang — APPROVED** [review]

**Pull request merged**
