### PR TITLE
Update spec-compliance-matrix RecordException for Go

### PR DESCRIPTION
**Pull request by MrAlias**
See https://github.com/open-telemetry/opentelemetry-specification/issues/764 for more detail.

Resolves https://github.com/open-telemetry/opentelemetry-go/issues/1595

### CODE REVIEW

**Comment by tigrannajaryan** [comment]
Was there a decision made that Go won't have RecordException? Reading https://github.com/open-telemetry/opentelemetry-specification/issues/764 I cannot see a resolution.

**Review by carlosalberto — APPROVED** [review]

**Comment by MrAlias** [comment]
@tigrannajaryan it is still an active discussion in https://github.com/open-telemetry/opentelemetry-go/issues/1491. We would like to provide idiomatic handling of errors and panics but it is still unclear how this will map to exceptions. We plan to update this if things change.

**Comment by tigrannajaryan** [comment]
> @tigrannajaryan it is still an active discussion in [open-telemetry/opentelemetry-go#1491](https://github.com/open-telemetry/opentelemetry-go/issues/1491). We would like to provide idiomatic handling of errors and panics but it is still unclear how this will map to exceptions. We plan to update this if things change.

@MrAlias Should we wait for the outcome of that discussion before marking this N/A in case it turns out not to be N/A? Or do you already know that it is definitely going to be a different approach for Go, so this line item is N/A no matter what is eventually decided?

**Comment by MrAlias** [comment]
> @MrAlias Should we wait for the outcome of that discussion before marking this N/A in case it turns out not to be N/A? Or do you already know that it is definitely going to be a different approach for Go, so this line item is N/A no matter what is eventually decided?

Sure, sounds good :+1:

**Pull request closed without merging**
