### PR TITLE
Fix typo of service.id -> service.instance.id

### PR DESCRIPTION
**Pull request by jrcamp**
## Changes

Note was referencing service.instance.id but called it service.id.

### CODE REVIEW

**Review by bogdandrutu — APPROVED** [review]

**Review by tigrannajaryan — APPROVED** [review]

**Comment by tigrannajaryan** [comment]
The checker is not happy about the change for some reason.

**Comment by jrcamp** [comment]
@tigrannajaryan I also found service.id used in logs and changed it to service.instance.id. Is that correct?

**Comment by jrcamp** [comment]
Oh I should have looked closer. It was in the section mapping the elasticsearch schema. I'm going to revert that since I don't know enough about it to fix it with confidence.

**Comment by jrcamp** [comment]
@tigrannajaryan build is fixed

**Comment by tigrannajaryan** [comment]
Merging, just a typo fix.

**Pull request merged**
